### ISSUE TITLE
Could we unify command line args with INSTA_UPDATE?

### ISSUE THREAD

**Issue by max-sixty** [mitsuhiko/insta#100]
It's very possible I'm missing something, but at the moment do we have some potential confusion for users between command line args and the `INSTA_UPDATE` env variable?

Specifically, I think most of the options in `INSTA_UPDATE` can't be replicated by command line args passed to `cargo insta test` except for:
- `INSTA_UPDATE=always` is equivalent to passing `--accept`
- `--force-update-snapshots` doesn't have an equivalent (though maybe makes sense as it's a one-off)

Should we make `INSTA_UPDATE=new` and `INSTA_UPDATE=no` available as command line args? And, if I've understood the `always` <> `accept` equivalence, unify the names, or at least offer the same name as an option?

Something like `--update=new` / `--update=always` / `--update=force`?

**Comment by max-sixty** [comment]
@mitsuhiko I have a few days spare, let me know if you have thoughts and I could do some work on this.

**Comment by mitsuhiko** [comment]
Yeah. Would be okay with a patch here.

**Comment by max-sixty** [comment]
FYI I started a new job since your message, so still keen on this but won't be able to do it in the near term. If someone else wants to make progress, feel free to take.

**Comment by mitsuhiko** [comment]
I'm closing this as I'm unsure if this is still something that needs to be done.
