### ISSUE TITLE
Miscreant dash in command line help?

### ISSUE THREAD

**Issue by max-sixty** [mitsuhiko/insta#101]
```
cargo insta test --help
cargo-insta-test 0.13.0
Run tests and then reviews

USAGE:
    cargo-insta test [OPTIONS]
```

Should that last line have a dash in `cargo-insta`? That command doesn't work for me and I've always run `cargo insta`...

**Comment by mitsuhiko** [comment]
Fixed in 0e801b3b1ad1aafafde1764a0ec1549dacaf40ee
