### ISSUE TITLE
Feature request: make console an optional dependency

### ISSUE THREAD

**Issue by matklad** [mitsuhiko/insta#102]
At the moment `insta` library uses `console` as a dependency, which pulls in a number of other deps, including heavy ones like `regex`. My understanding is that this is not the core functionality: monochrome diffs are workable, and you always can use `insta` *binary* to get extra colors. So, for users which want to minimize dependencies, it would be beneficial if `console` could be disabled.

**Comment by mitsuhiko** [comment]
I rather cut down on the dependencies of console. Regex in particular could be made optional if certain features are removed.
