### ISSUE TITLE
Support for inline string snapshot with newlines

### ISSUE THREAD

**Issue by sergeysova** [mitsuhiko/insta#107]
My result:

![image](https://user-images.githubusercontent.com/5620073/77253073-3b458880-6c69-11ea-891c-b0003f061bd2.png)

I want something like this:

![image](https://user-images.githubusercontent.com/5620073/77253097-5ca67480-6c69-11ea-8e6c-f13c603c1e2f.png)

I want to print newlines and tabs as is.

Now I use this workaround: print `Vec<String>` instead of `String`:
![image](https://user-images.githubusercontent.com/5620073/77253142-90819a00-6c69-11ea-9c3f-1244b856ed0a.png)

**Comment by max-sixty** [comment]
I'm surprised this isn't working. Do you have a reproducible example?

**Comment by sergeysova** [comment]
@max-sixty Here — https://github.com/sergeysova/actix-swagger/blob/master/cargo-swagg/src/printer/api/methods.rs

https://github.com/sergeysova/actix-swagger/blob/master/cargo-swagg/src/test.rs

**Comment by sergeysova** [comment]
Sorry, it's my fault. I should use `assert_snapshot` instead of `assert_yaml_snapshot`

**Comment by max-sixty** [comment]
:)

And TBC `assert_yaml_snapshot` should have inline line breaks. If that were happening because of insta rather than the yaml serialization, I think that's a bug — please post here if that's the case.
