### ISSUE TITLE
Using with rstest + actix puts snapshots in the wrong place

### ISSUE THREAD

**Issue by sazzer** [mitsuhiko/insta#122]
I'm not sure if this is an issue with Insta or with [rstest](https://github.com/la10736/rstest), so apologies if this is the wrong place.

When I'm using Insta with normal tests, it places the snapshots in a directory directly adjacent to the test. Which is great.

When I'm using Insta with parameterised tests from rstest, It's putting the snapshots directory in the root of the crate - in my case this means in `tests/snapshots` instead of `tests/tests/users/snapshots`.

It's not a problem at all - the filenames all have the module path in them so they're all guaranteed to be unique anyway - but it's a bit strange that they move around depending on whether I'm using rstest or not.

Cheers

**Comment by sazzer** [comment]
Further to this, it seems that it's only tests using rstest AND actix that do this.

I'm currently migrating from Actix to Rocket, and the tests that use rstest but are not async are putting the snapshots exactly where I'd expect to find them.

**Comment by mitsuhiko** [comment]
If you can provide a simple test case I could investigate. The path handling in rust tests is generally quite tricky and I need to do a few workarounds to get this working well. Likely macros expand at the wrong place.

**Comment by mitsuhiko** [comment]
Going to close due to inactivity.
