### ISSUE TITLE
One test no passed

### ISSUE THREAD

**Issue by tim77** [mitsuhiko/insta#126]
```rust
thread 'runtime::test_format_rust_expression' panicked at 'snapshot assertion
for 'format_rust_expression' failed in line 90', src/runtime.rs:995:9
```
[Full build log](https://download.copr.fedorainfracloud.org/results/atim/rust-crates/fedora-rawhide-x86_64/01477043-rust-insta/builder-live.log.gz) without this test.

Can we fix this or this is safe to skip?

**Comment by mitsuhiko** [comment]
This tests invokes `rustfmt` for formatting. Could it be that you do not have `rustfmt` on the path?

**Comment by tim77** [comment]
@mitsuhiko indeed. Thanks a lot.
