### ISSUE TITLE
`error: Unexpectedly did not find Cargo.toml in workspace`

### ISSUE THREAD

**Issue by chocol4te** [mitsuhiko/insta#13]
Hello!

If this is expected behaviour then please ignore, but if I have a workspace where members have `insta` tests, then I have to run `cargo insta review` in every directory, as opposed to being able to run it in the workspace, which gives the title output.

**Comment by mitsuhiko** [comment]
Do you have an example of how this workspace is set up? Is the root empty?

**Comment by chocol4te** [comment]
Sorry, for the delay, if you clone https://github.com/chocol4te/insta_workspace, run `cargo test` then `cargo insta review` you will get the title output.

The root is empty, is that the issue?

**Comment by mitsuhiko** [comment]
Yeah, likely. I had various issues with empty workspaces and cargo and vscode. Not sure yet how to deal with that.

**Comment by chocol4te** [comment]
I'm really sorry, I also only just learned about the `--all` flag which was exactly what I was looking for. Sorry for troubling you :/
