### ISSUE TITLE
Make prepending module to the snapshot filename optional

### ISSUE THREAD

**Issue by twilco** [mitsuhiko/insta#133]
Hi there!  Love this crate, thanks for creating it.

By default, insta snapshot filenames look like this:

`<module>__<name>.snap`

I'd like the option to make them look like this:

`<name>.snap`

Could this be a fit for the `Settings` struct?  Perhaps a `bool` flag to enable and disable this module prepending behavior, default enabled.  Named something like `prepend_module_to_snapshot`?

**Comment by mitsuhiko** [comment]
I think this could become an option. It's a bit risky though as insta has a hard time detecting duplicates.

**Comment by mitsuhiko** [comment]
Implemented in 38ae195d7f8438770d5baf27aba44b95838d12d3

**Comment by twilco** [comment]
Very late in my reply, but thanks for doing this!  Just found another use for it today :slightly_smiling_face:
