### ISSUE TITLE
Allow for `FnMut`in redactions

### ISSUE THREAD

**Issue by llogiq** [mitsuhiko/insta#143]
I have a use case where we want to check random but reused IDs, so what I tried was an `FnMut` that keeps a `Vec` with all IDs encountered and basically replaces them with incrementing numbers in order of first appearance. However, doing so, I found that `dynamic_redaction` will only accept `Fn`s.

Thinking a bit more about that, what we probably really want is a `Fn() -> Box<dyn FnMut(Content, ContentPath<'_>) -> Content>` to be able to get a new replacer for each snapshot test.

**Comment by mitsuhiko** [comment]
So generally `FnMut` doesn't really help here because I can only store `'static` closures on the settings. Making these stack borrows is pretty tricky. For your use case you should be able to get away with `Fn` though:

```rust
fn test_with_random_value_inline_mutable_callback() {
    let called = Arc::new(Mutex::new(vec![]));
    let called_inner = called.clone();
    assert_yaml_snapshot!("user", &User {
        id: 23,
        username: "john_doe".to_string(),
        email: Email("john@example.com".to_string()),
        extra: "".to_string(),
    }, {
        ".id" => insta::dynamic_redaction(move |value, path| {
            called_inner.lock().unwrap().push(path.to_string());
            assert_eq!(path.to_string(), ".id");
            assert_eq!(value.as_u64().unwrap(), 23);
            "[id]"
        }),
    });
    assert_eq!(*called.lock().unwrap(), vec![".id".to_string()]);
}
```
