### ISSUE TITLE
Provide pre-built binaries

### ISSUE THREAD

**Issue by njam** [mitsuhiko/insta#144]
Would you consider adding pre-built binary releases of "cargo-insta"?  
The main advantage would be faster installation time.

The binary compiles fine using the MUSL toolchain, so that would be an option for Linux:
```
cargo run --target x86_64-unknown-linux-musl -- --version
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/x86_64-unknown-linux-musl/debug/cargo-insta --version`
cargo-insta 1.3.0
```

**Comment by mitsuhiko** [comment]
I'm not sure if I have time enough to maintain binary builds at the moment. They are kinda painful and once you start doing them, people expect that they cover all platforms.

**Comment by njam** [comment]
Completely understand that.
I'd be happy to help, but I think it's not so easy to, because one needs administrative access to project and CI config.
