### ISSUE TITLE
Dependency `difference` is not maintained anymore

### ISSUE THREAD

**Issue by kper** [mitsuhiko/insta#153]
## Description

It seems like that the crate `difference` is not maintained anymore. https://github.com/johannhof/difference.rs/issues/45
This is very annoying because it was reported to RUSTSEC and therefore running `cargo audit --deny warnings` will fail in my CI.

## Reproduction steps

1. `git clone https://github.com/mitsuhiko/insta`
2. `cargo install cargo-audit` (if not installed)
3. `cd insta && cargo audit --deny warnings`

Additional helpful information:

- Version of insta: `1.5.2`

## Output

```
Crate:         difference
Version:       2.0.0
Warning:       unmaintained
Title:         difference is unmaintained
Date:          2020-12-20
ID:            RUSTSEC-2020-0095
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0095
Dependency tree: 
difference 2.0.0
└── insta 1.5.2

error: 1 denied warning found!
```

**Comment by mitsuhiko** [comment]
I find it quite annoying that RUSTSEC complains about unmaintained crates. The crate works fine, it has zero dependencies. I wish RUSTSEC would stop complaining about every single crate that is supposedly unmaintained.

**Comment by mitsuhiko** [comment]
I wrote the author to figure out if there is interest in someone else maintaining the crate.

**Comment by kper** [comment]
Thank you very much!
Let's see what he has to say

**Comment by mitsuhiko** [comment]
I did not get a response from the author. I however also ran into issues with the crate independently and started work on a difference crate to replace. https://github.com/mitsuhiko/similar
