### ISSUE TITLE
CSV with iterable of elements creates only 2 lines (header+content)

### ISSUE THREAD

**Issue by woshilapin** [mitsuhiko/insta#156]
## Description

I believe [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=31c708fb85bc4d0a1e304d9583e9a7bb) explains the problem. When we `.serialize()` a `Vec` of objects that implements `Serialize` with the `Serializer` of the `csv` crate, it doesn't create a line for each object but flatten them together. There might be good reasons to do it in `csv` but it does make `assert_csv_snapshot!()` not really useful. I hope I did not miss an obvious solution to what I'm trying to do. And also, I was not sure to report this as a bug or as a feature so please forgive me if that's not the right category.

Additional helpful information:

- Version of insta: 1.5.2
- Version of rustc: 1.49.0
- Operating system and version: Linux Ubuntu 20.10

## What did you expect

I would expect to be able to send a `Vec` or any kind of iterator of objects implementing `Serialize`, to the macro `assert_csv_snapshot!()` and be able to have a multiline `*.snap` instead of a 2-lines (one header line + one content line).

**Comment by mitsuhiko** [comment]
Yep. I also ran into this and I think the current format is not particularly useful. Would accept a PR to modify this behavior but currently relatively low priority for myself to fix this.

**Comment by woshilapin** [comment]
I wanted to be sure that it could not be solved at a higher level, but I would say that BurntSushi/rust-csv#221 is a pretty clear answer about it.

I might take a look at how to improve the behavior of `assert_csv_snapshot!()`.

**Comment by woshilapin** [comment]
Thank you for the fix! That is just perfect!
