### ISSUE TITLE
Collision between test names e.g. "foo" and "test_foo" causes nondeterministic result

### ISSUE THREAD

**Issue by ninevra** [mitsuhiko/insta#157]
## Description

If two tests have names that differ only by a `test_` prefix, then `insta` may confuse their snapshots, producing an intermittent test failure that likely depends on which test runs first.

## Reproduction steps

1. Set up test cases that differ only by a `test_` prefix:
```rust
#[cfg(test)]
mod tests {
    use insta;

    #[test]
    fn something() {
        insta::assert_snapshot!("foo");
    }

    #[test]
    fn test_something() {
        insta::assert_snapshot!("bar");
    }
}
```
2. Run `cargo test`, `cargo insta accept` to initialize snapshots. The snapshot files will be named `<crate_name>__tests__something.snap` and `<crate_name>__tests__something-2.snap`.
3. Run `cargo test` repeatedly. Sometimes tests will pass, and sometimes they will fail, having compared against the other test's snapshot.

Additional helpful information:

- Version of insta: 1.5.2
- Version of rustc: 1.49.0
- Operating system and version: Ubuntu 20.04

## What did you expect

The tests should correctly locate their snapshots and pass.

**Comment by mitsuhiko** [comment]
That is currently a known limitation. The `test_` prefix is discarded intentionally to make better looking snapshots but it does produce this result. I'm not sure if I can fix that without removing the automatic `test_` stripping.
