### ISSUE TITLE
"u128 is not supported"

### ISSUE THREAD

**Issue by sage-tpfs** [mitsuhiko/insta#167]
## Description

While attempting to snapshot test a value of a type I don't fully control I bumped into this error:

```
thread 'tests::u128_max_snapshot' panicked at 'called `Result::unwrap()` on an `Err` value: Error("u128 is not supported")', /home/sage/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.6.3/src/serialization.rs:98:55
```

## Reproduction steps

Observe that the first test below works without issue, whereas after removing the `ignore` the second causes the above error:

```rust
use insta::{assert_snapshot, assert_json_snapshot};

#[test]
fn u64_max_json_snapshot() {
    assert_json_snapshot!(u64::MAX);
}

#[test]
#[ignore = "u128 is not supported"]
fn u128_max_json_snapshot() {
   assert_json_snapshot!(u128::MAX);
}                                                                                                               
```

Additional helpful information:

- Version of insta: `1.6.3`
- Version of rustc: `rustc 1.50.0 (cb75ad5db 2021-02-10)`
- Operating system and version: `Pop!_OS 20.10`

## What did you expect

I expected JSON snapshots to work with values containing `u128`s. Admittedly, I may be missing some nuance here related to JSON, but this workaround suggests it's not an issue with `serde_json` preventing `u128` serialization.

```rust
#[test]                                                                                                                    
fn u128_max_snapshot() {                                                                                                   
    assert_snapshot!(serde_json::to_string_pretty(&u128::MAX).unwrap());                                                   
}                                                                                                                          
```

**Comment by mitsuhiko** [comment]
This is currently intentional. `u128` support would have to be implemented conditionally based on this: https://docs.serde.rs/serde/macro.serde_if_integer128.html

**Comment by sage-tpfs** [comment]
Ah, that makes a lot of sense. Thanks!

Would you be interested in a PR for this? I can spend some time on it this weekend.
