### ISSUE TITLE
Test fails but review says snapshots are matching

### ISSUE THREAD

**Issue by JohnnyMorganz** [mitsuhiko/insta#170]
## Description

I am using insta for some snapshot testing for a code formatter.
For some tests, I run `cargo insta test --review`, and accept the new snapshot for the new test.
I then run `cargo insta test --review` again, and insta picks up on some sort of difference (there shouldn't be any difference), but in the review stage, it says the snapshots are matching (as expected):

```
Reviewing [1/1]:
Package: stylua (0.4.1)
Snapshot file: tests\snapshots\tests__standard@ignore-comment.lua.snap
Snapshot: standard@ignore-comment
Source: C:\Users\Development\Documents\luafmt
-old snapshot
+new results
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
format(&contents)
────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
          - │ snapshots are matching
────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  a accept   keep the new snapshot
  r reject   keep the old snapshot
  s skip     keep both for now
```

This causes the test to fail, even though the snapshots are exactly the same.

### Sample input file (loaded in through using `insta::glob()`)
```lua
-- stylua: ignore
local   bar    =   baz

```

Output when running the test is equal to the above input file

### Corresponding snap file
```yaml
---
source: tests/tests.rs
expression: format(&contents)

---
-- stylua: ignore
local   bar    =   baz

```
Additional helpful information:

- Version of insta: 1.6.3
- Version of rustc: 1.48.0 (7eac88abb 2020-11-16)

**Comment by mitsuhiko** [comment]
I wonder if a trailing or missing trailing newline is doing this. Can you check if there is something going on where you have differences in newline behavior that might be explaining this?

**Comment by JohnnyMorganz** [comment]
Just checked, no trailing whitespace anywhere in the input - the `.snap` file though does have a newline at the end, when the input does not (although this seems to be added for all snap files it seems)

One suprising thing that I just noticed though, if I remove the comment (`-- stylua: ignore`), and change the input to a formatted version, (meaning no change done by my formatter), the test passes fine - no difference detected by insta (as expected)
```lua
local bar = baz
```
If I then try a completely formatted version, with the comment back in (as shown below), insta picks something up again, with the `snapshots are matching` message
```lua
-- stylua: ignore
local bar = baz
```

**Comment by mitsuhiko** [comment]
Do you by any chance have a minimal repro case for this?

**Comment by mitsuhiko** [comment]
@JohnnyMorganz I absolutely cannot reproduce this issue.

**Comment by JohnnyMorganz** [comment]
@mitsuhiko Sorry, I missed your previous reply.
I've been looking at this further, and I think there is a partial error on my part, with the combination of an issue with line endings.
The input snippets I gave, they were originally using CRLF line endings (I am going to move them all the LF on my end). The formatter *should have* changed all the line endings to LF, but it seems to miss it for any lines containing a comments, and they remained as CRLF.

Relevant to insta:
I think insta changes all the line endings to LF in the snapshots itself, so the issue that is arising is that there is a single line with the wrong line ending, which is the difference that its picking up.
I guess the main issue here then is that the review stage doesn't show this difference in line endings, leading to the "snapshots are matching" error

**Comment by mitsuhiko** [comment]
Going to open up a separate issue for that.
