### ISSUE TITLE
rustfmting the source expression in cargo insta review is wrong in the general case

### ISSUE THREAD

**Issue by CAD97** [mitsuhiko/insta#177]
## Description

I'm using insta to test the parser for my personal toy scripting language. As such, the exact formatting of the input expression is quite important. In order to display the actual tested input rather than just a lot of "`parse(input)`", I'm currently using the following as my main test harness:

```rust
#[test]
fn parse_snapshot_tests() {
    insta::glob!("nafi/*.nafi", |path| {
        let input = std::fs::read_to_string(path).unwrap();
        let parsed = format!("{:#?}", SourceFile::parse(&input).syntax_tree());
        insta::assert_snapshot!("parse", parsed, &input);
    });
}
```

In the actual snapshot files, all is well and good:

```yaml
---
source: crates/syntax/tests/snapshots.rs
expression: 1+2*3/4-5
---
SourceFile@0..9
  Expr@0..9
    Expr@0..7
      Expr@0..1
        LitDigits@0..1 "1"
      Syntax@1..2 "+"
      Expr@2..7
        Expr@2..5
          Expr@2..3
            LitDigits@2..3 "2"
          Syntax@3..4 "*"
          Expr@4..5
            LitDigits@4..5 "3"
        Syntax@5..6 "/"
        Expr@6..7
          LitDigits@6..7 "4"
    Syntax@7..8 "-"
    Expr@8..9
      LitDigits@8..9 "5"

```

but when reviewing changes in `cargo insta review`, I noticed that the input was formatted differently. In fact, `cargo insta`'s review preview runs the expression stored in the snapshot through rustfmt:

https://github.com/mitsuhiko/insta/blob/4677798860c60ab3a4dec8b18ac08ecafe4673c7/src/runtime.rs#L219

## What did you expect

`cargo insta` should be displaying the expression in the snapshot file as-is. If the expression is to be rustfmt'd, this should happen when writing the snapshot, not when reading it. The metadata in the snapshot file itself should be treated as authoritative.

`assert_snapshot!( "name", "snapshot", "expression" )` probably should respect what the caller wrote, and not rustfmt the input expression.

## Additional helpful information:

- Version of insta:
  cargo-insta 1.7.1
  insta 1.5.1
- Version of rustc: rustc 1.52.0-beta.2 (4f27db695 2021-03-26)
- Operating system and version: Microsoft Windows Version 20H2 (OS Build 19042.867)

**Comment by mitsuhiko** [comment]
I think this is something we could do some experiments with. Happy to accept a PR that changes where the formatting happens. That said, this is likely going to cause some frustrating for existing users since all the sudden the standard experience will be a (rather large) multi-line string in the header. That might make snapshot files harder to inspect.

**Comment by CAD97** [comment]
#168 explicitly wants multiline snippets for the input string, so perhaps the fix to these could go hand in hand.

**Comment by CAD97** [comment]
> the standard experience will be a (rather large) multi-line string in the header. That might make snapshot files harder to inspect.

Well, when serializing, the string will always be a single line "`"`-string" anyway (with the yaml metadata format), so it'll be on one line anyway. So single-line Rust expressions would be easier to read (as they're properly formatted), and multiline expressions are maybe longer on-disk for their embedded formatting, but still otherwise not really useful, as they're on a single line still.
