### ISSUE TITLE
Basic `cross` compilation support

### ISSUE THREAD

**Issue by jeysal** [mitsuhiko/insta#178]
Snapshot tests always fail when run using [cross](https://github.com/rust-embedded/cross) e.g. for target Windows from Linux.
I realize this may be all but trivial to solve, but creating this so at least it's tracked. I have marked it as a feature request instead of calling it a bug.

However, IMO literally just `test` and none of the review functionality would be required to work in `cross` (you can use your own target to review, and then use `cross` just to test the written snapshot for other targets).
And even then, if just inline snapshots that would work that would already help a lot of people who don't need snapshot files. Just `test`ing with `cross` working just for inline snapshots which don't need file I/O may be a somewhat realistically achievable goal? I don't really know much about internal workings of either `cross` or `insta`.

[Repro](https://github.com/jeysal/cross-insta-repro) - It's really just a crate with insta and one inline snapshot test added.

Running `cargo test` works.
Running `cross test --target=x86_64-pc-windows-gnu` (on x86_64 GNU/Linux) fails with:
```
thread 'tests::test' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Other, message: "Invalid handle." }', /cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.7.1/src/runtime.rs:202:14
```

**Comment by mitsuhiko** [comment]
Basically it appears to fail invoking `cargo metadata`. Is there something specific one has to do to make this work within an environment that cross invokes?

**Comment by jeysal** [comment]
Hmm yeah I was just trying to dig a bit deeper as well.
A quick `println!("{}", env!("CARGO"));` says that `CARGO` is being set to `/rust/bin/cargo`, which doesn't actually seem to exist in the image that cross runs. Maybe it's actually `cross` setting a weird environment variable for whatever reason...

**Comment by jeysal** [comment]
It seems they mount /rust in though. Will have to do more digging to find out what's happening, why `cargo` can't be run

**Comment by jeysal** [comment]
I have a feeling the OS error 6 invalid handle is basically "Windows" telling me I'm trying to run a Linux binary (cargo). This is further supported by the fact that `cross` with a target similar to my own seems to work with `insta`. So I guess either `cross` would need to support running `cargo` even in the Windows/Linux case, or `insta` would need to fall back to minimal functionality (no finding the cargo workspace root = no non-inline or pending snapshots) if cargo cannot be run.

**Comment by jeysal** [comment]
Created https://github.com/rust-embedded/cross/issues/550

**Comment by mitsuhiko** [comment]
I'm going to close this. There hasn't been a lot of activity and I'm not even sure if the original issue still applies. If this is still an issue please file a new one.
