### ISSUE TITLE
Pass a specific test to run in `cargo insta test`

### ISSUE THREAD

**Issue by JohnnyMorganz** [mitsuhiko/insta#182]
I have quite a few tests to go through, and when trying to get an updated snapshot, it takes some time to reach the test I want to update.
It would be useful if we could pass a specific test name to run when using `cargo insta test`, e.g. `cargo insta test --test <name>`.
This would be similar to how normal cargo test works, `cargo test --test <name>`. This would help quicken testing for me. I see there is already other args passed, such as `--release` and `--features`.

**Comment by grovesNL** [comment]
I was wondering about the same thing and whether we it would be possible to forward other arguments to `cargo test` more generally, e.g. arguments like `cargo test -- --test-threads=1`
