### ISSUE TITLE
Review multiple snapshots at once?

### ISSUE THREAD

**Issue by vedantroy** [mitsuhiko/insta#186]
I'm using insta in a project, and it seems like when I add multiple `assert_yaml_snapshot` (maybe just in the same method), I have to run `cargo insta review` and then rerun `cargo test` after I update each snapshot (I'm guessing insta panics after the first failure in a given method?)

Is there a way to get around this?

**Comment by mitsuhiko** [comment]
If you run `cargo insta test` it will force snapshots to pass which lets you review multiple at once.  You can also run `cargo insta test --review` to run test and review after each other.
