### ISSUE TITLE
Allow setting extension as .md instead of .snap

### ISSUE THREAD

**Issue by askbeka** [mitsuhiko/insta#188]
I think `.md` extension is quite flexible
it is also possible to print language specific within code blocks
~~~
```yaml
```
```rust
```
~~~

Benefit of this is that it can be used as documentation.
Especially for macros libraries, that get input as code generate code.

**Comment by mitsuhiko** [comment]
The downside is that the system assumes that files named `.snap` are snapshots. If the extension were `.md` we would be picking up unrelated files and tried to process them as snapshots.
