### ISSUE TITLE
`cargo test` panics when rustfmt is not installed

### ISSUE THREAD

**Issue by jordwest** [mitsuhiko/insta#19]
When `rustfmt` is not installed, the output ends with a panic:

```
thread 'block::tests::outputs_a_block_with_correct_indentation' panicked at 'byte index 14 is out of bounds of ``', src/libcore/str/mod.rs:2092:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

There is an error near the top of the output, but it's easy to miss:

```
error: 'rustfmt' is not installed for the toolchain 'stable-x86_64-apple-darwin'
To install, run `rustup component add rustfmt`
```

Could something like this error be printed instead of the out of bounds panic?

**Comment by mitsuhiko** [comment]
That was actually supposed to silently fall back but it did not properly check the status code.
