### ISSUE TITLE
"error: Incorrect function. (os error 1)" on review prompt under MSYS2

### ISSUE THREAD

**Issue by vilcans** [mitsuhiko/insta#195]
## Description

Running `cargo insta review` displays the diff and displays the prompt but it's followed immediately by an error:

```
  a accept   keep the new snapshot
  r reject   keep the old snapshot
  s skip     keep both for now
error: Incorrect function. (os error 1)
```

This is when I run the command under MSYS2 in Windows. The same command works if I run it in cmd.exe.

I suspect a bug in the console crate, but I haven't looked into it.

## Reproduction steps

1. Create a new test (or make an existing one have a diff).
2. Run `cargo insta review` in an MSYS2 prompt.

## What did you expect

The process shouldn't end with an error. 😄  And I don't want to use built-in command prompt in Windows.

**Comment by mitsuhiko** [comment]
Closing this here for now. Might be worth reopening for console.
