### ISSUE TITLE
[question] How to save into a single snap file for each rs file?

### ISSUE THREAD

**Issue by oxalica** [mitsuhiko/insta#197]
I'm writing simple snapshot tests to benefit from `insta`'s auto-update functionality. Thus in one test rs file, there are tens of assertions, while each one produces <10 lines of snapshot. Currenlty `insta` write each assertion result into separated files, leaving tens of `.snap` files around, which is kind of annoying.

I'd like to generate all assertion snapshot result of `foo.rs` into a single file like `foo.snap`, how can I do that?

BTW: I'm not using inline snapshots, since it cannot update ALL snapshots in a single run. `INSTA_UPDATE=always` results in `error: cannot update inline snapshots in-place`.

**Comment by mitsuhiko** [comment]
I think the best way is indeed to use inline snapshots and use `cargo insta test --all --review`. That gives you I believe the experience you want.

**Comment by oxalica** [comment]
> `cargo insta test --all --accept`

It works. Thanks for clarification.
