### ISSUE TITLE
Macro for loading an existing snapshot

### ISSUE THREAD

**Issue by FreeMasen** [mitsuhiko/insta#199]
For testing serialization round trips, having a way to lookup an existing snapshot would be nice.

For example something like this would be helpful:

```rust
use serde::{Serialize, Deserialize};

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct SomethingToTest {
    pub property: String,
    pub thing_that_will_be_converted: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
}

#[cfg(test)]
mod test {
    use super::*;
    
    #[test]
    fn something_to_test() {
        let expected = SomethingToTest {
            property: "property".to_string(),
            thing_that_will_be_converted: 100,
            optional: None,
        };
        insta::assert_json_snapshot!(expected);
        if let Some(exiting) = insta::find_snapshot!() {
            let round_trip: SomethingToTest = serde_json::from_str(exiting.contents_str()).unwrap();
            assert_eq!(expected, round_trip);
        }
    }
}

```

**Comment by mitsuhiko** [comment]
I think the idea is nice, but I'm not so happy with exposing this `Snapshot` type further. I will consider this, but this might be a good time to clean up that snapshot API a bit. It's also partially standing in the way of non string snapshots (refs #196)

**Comment by FreeMasen** [comment]
There are a few of alternatives that I can see being helpful for this use case that may fit better into you vision for this project. 

The first would be to provide some method for resolving the path for the existing test's `.snap` file. This would still rely on the `Snapshot` type and may complicate the non-string snapshots referenced above.

The other option would be to provide some method for resolving the deserializable type, this might require similar duplication as the assert macros provided by this lib (for example `find_snapshot_json!`, `find_snapshot_yaml!` and `find_snapshot_csv!` would could return `T: Deseralize` failing of the wrong macro is used for the snapshot type or the type failed to deserialize). For example:

```rust
#[test]
fn something_to_test() {
    let expected = SomethingToTest {
        property: "property".to_string(),
        thing_that_will_be_converted: 100,
        optional: None,
    };
    insta::assert_json_snapshot!(expected);
    if let Result::<SomethingToTest, _>::Ok(exiting) = insta::find_snapshot_json!() {
        let round_trip: SomethingToTest = serde_json::from_str(exiting.contents_str()).unwrap();
        assert_eq!(expected, round_trip);
    }
}
```

A third option would be to provide something the fetches the string like `insta::find_snapshot_string!` which would return an `Option<String>` that would then be `None` for not-yet-generated snapshots or for non-string shapshots.

**Comment by mitsuhiko** [comment]
Since this already does not work for inline snapshots I wonder if the better way for such cases is not to dump to JSON yourself, then just do `assert_snapshot!` like this:

```rust
#[test]
fn something_to_test_alt() {
    let expected = SomethingToTest {
        property: "property".to_string(),
        thing_that_will_be_converted: 100,
        optional: None,
    };
    let expected_json = serde_json::to_string_pretty(&expected).unwrap();
    insta::assert_snapshot!(expected_json);
    let round_trip: SomethingToTest = serde_json::from_str(exiting.contents_str()).unwrap();
    assert_eq!(expected, round_trip);
}
```

I tried a few things now and I'm not entire sold on the idea that reading snapshot contents back is useful in general, particularly as most of these use cases will involve round-tripping and here the redaction system will already not work with it most likely.

**Comment by FreeMasen** [comment]
That is a much better method for handling this kind of test, thank you!
