### ISSUE TITLE
`cargo test` fails with: "error[E0432]: unresolved import `insta::assert_serialized_snapshot_matches"`

### ISSUE THREAD

**Issue by jankeromnes** [mitsuhiko/insta#2]
Hello! I work on [Gitpod](https://gitpod.io), and I just wanted to make sure that compiling Insta works well in Gitpod.

I basically just tried `cargo build` and `cargo test`, but the latter failed and I don't understand why:

```
error[E0432]: unresolved import `insta::assert_serialized_snapshot_matches`
 --> tests/test_basic.rs:3:44
  |
3 | use insta::{assert_debug_snapshot_matches, assert_serialized_snapshot_matches};
  |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `assert_serialized_snapshot_matches` in the root. Did you mean to use `assert_debug_snapshot_matches`?

error: cannot determine resolution for the macro `assert_serialized_snapshot_matches`
  --> tests/test_basic.rs:12:5
   |
12 |     assert_serialized_snapshot_matches!("serialized_vector", vec![1, 2, 3]);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `insta`.
```

`E0432` seems to suggest adding `extern crate insta;` but that's already present:

https://github.com/mitsuhiko/insta/blob/a0e1e84901cc368b1644742ab8e9dc8ca225228d/tests/test_basic.rs#L1

I've made a "Gitpod snapshot" to demonstrate the issue (clicking on it will take you to an online workspace where Insta was cloned, `cargo build` was run, and `cargo test` will run and fail):

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/6d26c8c5-80e9-4644-96f0-fc89183b7065)

Could you please help me understand this issue?

**Comment by max-sixty** [comment]
You need to enable that feature; you can see the exact command in makefile

**Comment by jankeromnes** [comment]
Thank you @max-sixty! This solved my issue. I've documented the Makefile-based workflow in `README.md` and will open a pull request. 👍
