### ISSUE TITLE
cargo insta test -p <crate> --delete-unreferenced-snapshots deletes snapshots from other crates

### ISSUE THREAD

**Issue by tschilling-natzka** [mitsuhiko/insta#201]
## Description

I have a repository with multiple cargo crates inside of it. Usually, when I'm working on one package I run the tests from the IDE, or via `cargo test -p mycrate`.

I wanted to clean up the snapshots for one crate, so I ran `cargo insta test -p mycrate --delete-unreferenced-snapshots`, but that deleted _all_ snapshots from all the other crates. Fortunately, they were already all committed in Git, so I could restore them.

## Reproduction steps

1. Create a multi-crate package. E.g.,
```
mkdir testdir
cd testdir
git init
mkdir crates
echo '[workspace]
members = ["crates/*"]
' > Cargo.toml
cd crates
cargo new --lib crate1
cargo new --lib crate2
```
Then add some insta tests for both crate1 and crate2.
Commit your changes.

2. From the top-level directory, run: `cargo insta test -p crate1` This should only run the tests from crate1.
3. Now run it again via `cargo insta test -p crate1 --delete-unreferenced-snapshots` deletes all snapshots from `crate2` because we only run tests from `crate1` which don't reference any snapshots of from `crate2`

Additional helpful information:

- Version of insta: 1.8.0
- cargo-insta 1.8.0
- Version of rustc: 1.57.0
- Operating system and version: Linux

## What did you expect

Snapshots for packages other than `crate1` should remain untouched.

BTW, it would also be nice to have a dry-run mechanism to be able to preview which files will be deleted before they actually are deleted.

**Comment by mitsuhiko** [comment]
Unfortunately this is a known limitation as insta does not get any information about which crate is being tested from the rust test framework. A workaround is to go into the correct crate folder and run the tests from there. I'm not sure is there is a way to fix this with what's currently available from the test system.

**Comment by tschilling-natzka** [comment]
Hm. I thought it might be possible to simply look at the `-p/--package` parameter and then ensure that you only delete snapshots from that package. But maybe you don't have enough info to figure out which directory belongs to a specific package?
