### ISSUE TITLE
Deterministic sort order for HashSet (reopen issue #53)

### ISSUE THREAD

**Issue by mdharm** [mitsuhiko/insta#211]
### What happened?

This is a re-open of issue #53 

While the discussion in that issue claims that using `settings.set_sort_maps(true)` would work on `HashSet`, it only seems to work on `HashMap`.  It should work on both.  This makes `insta` not practically usable for any struct that includes a `HashSet`.

### Reproduction steps

1. Apply patch below to a clone of `insta`
2. Run "cargo test"

```
diff --git a/tests/test_settings.rs b/tests/test_settings.rs
index e89454a..ed5fbec 100644
--- a/tests/test_settings.rs
+++ b/tests/test_settings.rs
@@ -1,5 +1,5 @@
 use insta::{assert_yaml_snapshot, with_settings, Settings};
-use std::collections::HashMap;
+use std::collections::{HashMap, HashSet};
 
 #[test]
 fn test_simple() {
@@ -23,6 +23,27 @@ fn test_simple() {
 }
 
 #[test]
+fn test_simple2() {
+    let mut map = HashSet::new();
+    map.insert("first value");
+    map.insert("second value");
+    map.insert("third value");
+    map.insert("fourth value");
+
+    let mut settings = Settings::new();
+    settings.set_sort_maps(true);
+    settings.bind(|| {
+        assert_yaml_snapshot!(&map, @r###"
+        ---
+        first value
+        second value
+        third value
+        fourth value
+        "###);
+    });
+}
+
+#[test]
 fn test_bound_to_thread() {
     let mut map = HashMap::new();
     map.insert("a", "first value");
```

Repeated executions will show that the `HashSet` is being serialized into a different order every time.

### Insta Version

Cloned from git on 24 Jan 2022

### rustc Version

1.57

### What did you expect?

I expected both `HashMap` and `HashSet` to be affected by setting `set_sort_maps(true)`, as a `HashSet` is simply a `HashMap` with a `Unit` value.

**Comment by mitsuhiko** [comment]
You're right that `HashSet`s are not retaining order. Unfortunately the issue with sets is that those are in serde's data model just lists. This means whatever order is the natural iteration order of the `HashSet` is what is passed to the serde serializer. I'm not aware of a way to detect hash sets and change this order unfortunately.

The only solution I can think of is to either provide a wrapper type one can use to force sorting of sets somewhere in the structure, to manually implement `Serialize` and sort the set manually before serializing, or some alternative API to force sorting for a specific selector.

Something like this could work:

```rust
fn my_test() {
    let mut settings = Settings::new();
    settings.sort_sequence(".my_seq");
    settings.bind(|| insta::assert_json_snapshot!(MyStruct {
        my_seq: hashset![1, 2, 3, 4],
    });
}
```

**Comment by mdharm** [comment]
That sort of approach would certainly work.  The only other idea I've come up with is to do something like this in my code:
```
#[cfg(not(test))]
use std::collections::HashSet;

#[cfg(test)]
use std::collections::BTreeSet as HashSet;
```

Of course, this only works because I'm only using methods that are common to both types and the natural iterator order for a BTreeSet is deterministic.  It does require that I also `#[derive(PartialOrd, Ord)]` on my structs as well.  And it's generally pretty ugly.

Being able to specify using a selector which sequences would be much cleaner.

**Comment by mitsuhiko** [comment]
@mdharm i implemented something in #211. Can you give feedback if this is addressing your use cases?

**Comment by mdharm** [comment]
This works perfectly for me.  I look forward to this being merged and a new version being released.

**Comment by mawkler** [comment]
Hi! I'm not sure if I'm doing something wrong but `HashSet`s seem to be non-deterministic still for me:

```rust
#[test]
fn foo_test() {
    insta::with_settings!({sort_maps => true}, {
        insta::assert_json_snapshot!(
            (
                std::collections::HashSet::from([2, 1, 3]),
                std::collections::HashMap::from([("one", 1), ("two", 2), ("three", 3)]),
             )
            );
    });
}
```

The `HashMap` seems to always have the same order, but the `HashSet`'s order in the snapshot changes between recompilations.

**Comment by mawkler** [comment]
Your fix seems to have solved my issue. Thank you!

Are there any plans to support configuring `sort_maps` globally from the `insta.yaml` config file?
