### ISSUE TITLE
Assertion numbers in snap files make test diffs noisy

### ISSUE THREAD

**Issue by phoglund** [mitsuhiko/insta#215]
### What happened?

```
@@ -1,6 +1,6 @@
 ---
 source: crates/my_code.rs
-assertion_line: 1773
+assertion_line: 1765
 expression: my_expr

 ---
```

This happens if the .snap file is rewritten for whatever reason. Fortunately tests don't fail if the line assert is the only thing that changes, but it has the side effect that the assert line is wrong if the source file changed in such a way it doesn't break the tests (since that .snap file was written).

### Reproduction steps

1. Change something that breaks a insta test
2. The assert line number changes in the snapshot

### Insta Version

1.8.0

### rustc Version

rustc 1.58.1 (db9d1b20b 2022-01-20)

### What did you expect?

I think the above is annoying because it causes noise in the diff, and I can't see why the information is useful.

Suggestion: a feature flags to take those .snap file headers away?

**Comment by mitsuhiko** [comment]
Generally the assertion line is primarily useful for snapshot reviews with `cargo-insta`. After the review concluded it does not really fulfill a purpose any more. One way to address this would be to only retain the `assertion_line` in the `.new` files.
