### ISSUE TITLE
Race Conditions with new naming convention

### ISSUE THREAD

**Issue by olliebatch** [mitsuhiko/insta#216]
### What happened?

Not sure of this is now a bug or a new feature request based on the latest 1.12 change

I've been using insta alongside another crate **rstest** which provides the ability to case based on singular functions.. 
E.G
`#[rstest]
#[case(0, 0)]
#[case(1, 1)]
#[case(2, 1)]
#[case(3, 2)]
#[case(4, 3)]
fn fibonacci_test(#[case] input: u32, #[case] expected: u32) {
    insta::assert_debug_snapshot!(fibonacci(input);
}`

Effectively this makes new threads for different cases - Before this would be handled by insta making the snapshot name **case_2**, **case_1**  from the thread name

The new version of insta makes this appear as **fibonacci_test** and **fibonacci_test_1**

As the tests are running at the same time, this can cause different tests to finish first and then compare against other tests snapshots.

Is there a suggestion that is recommended here now with the new approach to avoid race conditions?, would you expect to now require passing snapshot names to the tests to be able to run this?

### Reproduction steps

1. [First step]
`#[rstest]
#[case(0, 0)]
#[case(1, 1)]
#[case(2, 1)]
#[case(3, 2)]
#[case(4, 3)]
fn fibonacci_test(#[case] input: u32, #[case] expected: u32) {
    insta::assert_debug_snapshot!(fibonacci(input);
}`

2. Run tests continously and they will fail dependant on race conditions
3. etc.

### Insta Version

1.12

### rustc Version

1.58.1

### What did you expect?

Previously this appended each thread name with the case values. 

Just trying to understand a suggested approach with this change to not using thread names

**Comment by mitsuhiko** [comment]
This is an intentional change as names are no longer pulled from threads but function names. The thread based approach was too brittle. It's recommended to set a name in these cases explicitly.

**Comment by mitsuhiko** [comment]
I think this is best solved by explicitly setting a suffix. I added an example to the docs which I think is how this ideally gets used with `rstest`. This will also work for web assembly or cases, where thread names are broken or if concurrency is disabled: https://insta.rs/docs/patterns/#rstest

**Comment by holtgrewe** [comment]
@mitsuhiko What about adding this macro to the insta crate?

**Comment by mitsuhiko** [comment]
@holtgrewe which macro are you referring to?
