### ISSUE TITLE
'snapshot assertion for 'xxx function' failed in line x'

### ISSUE THREAD

**Issue by wulinsheng123** [mitsuhiko/insta#217]
### What happened?

wuls@XD021NB2003146 html-parse % cargo test                      
    Finished test [unoptimized + debuginfo] target(s) in 0.17s
     Running unittests (target/debug/deps/html_parser-d0821d9412cb4dab)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/test.rs (target/debug/deps/test-f990fbacdea69bff)

running 1 test
stored new snapshot /Users/wuls/Desktop/github/html-parse/crates/html_parser/tests/snapshots/test__it_works.snap.new
test it_works ... FAILED

failures:

---- it_works stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Differences ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: crates/html_parser/tests/snapshots/test__it_works.snap
Snapshot: it_works
Source: crates/html_parser/tests/test.rs:7
+new results
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
m
────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
          0 │+Node {
          1 │+    node_type: Text(
          2 │+        "example",
          3 │+    ),
          4 │+}
────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
thread 'it_works' panicked at 'snapshot assertion for 'it_works' failed in line 7', /Users/wuls/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.12.0/src/runtime.rs:391:9
stack backtrace:
   0:        0x106fc66e4 - std::backtrace_rs::backtrace::libunwind::trace::h03e89bdd1996f493
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x106fc66e4 - std::backtrace_rs::backtrace::trace_unsynchronized::hb5af08e4de8ca785
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x106fc66e4 - std::sys_common::backtrace::_print_fmt::h4eafc628aec41041
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x106fc66e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6a8908fa3ed6f9e8
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x106fe826c - core::fmt::write::h4be00f71c5582919
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:        0x106fc2c1a - std::io::Write::write_fmt::h93cbb8c6ac53b1a6
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:        0x106fc85bf - std::sys_common::backtrace::_print::h2f7b8ad2bea4f859
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x106fc85bf - std::sys_common::backtrace::print::h97402070cfceb1a3
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x106fc85bf - std::panicking::default_hook::{{closure}}::h1577f0656e419c0e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:        0x106fc80f6 - std::panicking::default_hook::h1aef594179c4fd25
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:222:9
  10:        0x106fc8cc0 - std::panicking::rust_panic_with_hook::h10bc487d002f6c42
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:        0x106fc8765 - std::panicking::begin_panic_handler::{{closure}}::hf4cfa78c105ce648
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:519:13
  12:        0x106fc6b58 - std::sys_common::backtrace::__rust_end_short_backtrace::h1df96a166e4351c4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x106fc86ca - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:        0x106ff792b - std::panicking::begin_panic_fmt::h926788b67afe29e5
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
  15:        0x106e6caa5 - insta::runtime::finalize_assertion::hc001ef275761e54d
                               at /Users/wuls/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.12.0/src/runtime.rs:391:9
  16:        0x106e6d0f8 - insta::runtime::assert_snapshot::haa7e665051b0aec0
                               at /Users/wuls/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.12.0/src/runtime.rs:445:9
  17:        0x106e09130 - test::it_works::h7d78dd784aa1ae3a
                               at /Users/wuls/Desktop/github/html-parse/crates/html_parser/tests/test.rs:7:5
  18:        0x106e08fa9 - test::it_works::{{closure}}::h065b87d07253ed84
                               at /Users/wuls/Desktop/github/html-parse/crates/html_parser/tests/test.rs:5:1
  19:        0x106e08649 - core::ops::function::FnOnce::call_once::hce919f7bdd05effa
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  20:        0x106e3095a - core::ops::function::FnOnce::call_once::h4cdcaabe83a67286
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  21:        0x106e3095a - test::__rust_begin_short_backtrace::h8537766c178d3dff
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/test/src/lib.rs:577:5
  22:        0x106e2f5ee - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he7f1d442cbf186ee
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
  23:        0x106e2f5ee - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h0539be0c88882132
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347:9
  24:        0x106e2f5ee - std::panicking::try::do_call::h9934dd4d1098ebe5
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  25:        0x106e2f5ee - std::panicking::try::h6c385dccc769be1e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  26:        0x106e2f5ee - std::panic::catch_unwind::h82f43efc74044115
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  27:        0x106e2f5ee - test::run_test_in_process::h9940108790aaa2de
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/test/src/lib.rs:600:18
  28:        0x106e2f5ee - test::run_test::run_test_inner::{{closure}}::hef20bc7b3073ef89
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/test/src/lib.rs:492:39
  29:        0x106e094f0 - test::run_test::run_test_inner::{{closure}}::hc793c481e1a301b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/test/src/lib.rs:519:37
  30:        0x106e094f0 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbedd640dcb83f549
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:125:18
  31:        0x106e0d264 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h9b7e6216d8f93ce4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:481:17
  32:        0x106e0d264 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha8ef54676c5cb48d
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347:9
  33:        0x106e0d264 - std::panicking::try::do_call::hb8843062a4e60741
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  34:        0x106e0d264 - std::panicking::try::h3f23199fae8f2324
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  35:        0x106e0d264 - std::panic::catch_unwind::h6bbb1cd76fdffb88
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  36:        0x106e0d264 - std::thread::Builder::spawn_unchecked::{{closure}}::hfbdb80e7c5ac8fb9
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:480:30
  37:        0x106e0d264 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hbeed65ddf37019e1
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  38:        0x106fce17b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd1aaf96bb4a825cd
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
  39:        0x106fce17b - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h85328f151de296fc
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
  40:        0x106fce17b - std::sys::unix::thread::Thread::new::thread_start::h63f8b299c7b9d50c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys/unix/thread.rs:71:17
  41:     0x7fff204ab8fc - __pthread_start

failures:
    it_works

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.24s

error: test failed, to rerun pass '-p html_parser --test test'
wuls@XD021NB2003146 html-parse % 

expect : success 

**I tried `cargo insta review` before** 

**but**  

wuls@XD021NB2003146 html-parse %  cargo insta review       
error: no such subcommand: `insta`
 Did you mean `init`?

### Reproduction steps

1. cargo insta review
2. cargo test

### Insta Version

1.10.0

### rustc Version

rustc 1.54.0 (a178d0322 2021-07-26)

**Comment by mitsuhiko** [comment]
You did not install `cargo-insta` from what I can tell. Run `cargo install cargo-insta`.
