### ISSUE TITLE
Support for async functions with glob!

### ISSUE THREAD

**Issue by sazzer** [mitsuhiko/insta#219]
The `glob!` macro is an awesome way to write a single test that runs on a number of different inputs. However the fact that it only takes synchronous callbacks is slightly awkward in some cases.

I'm able to use it in an async setting as follows:
```rust
        glob!("snapshots/patch_validation_failure-*.input.json", |path| {
            let runtime = tokio::runtime::Builder::new_current_thread()
                .build()
                .unwrap();
            runtime.block_on(async {
                ..... Test here .....
            }
        });
```

But it is slightly clunky. It would be slightly better if I could instead do:
```rust
        glob!("snapshots/patch_validation_failure-*.input.json", async |path| {
                ..... Test here .....
        });
```

Cheers

**Comment by mitsuhiko** [comment]
My recommendation would be to create a wrapper macro for this. This is unlikely to be solved in insta itself due to the many different ways in which someone might want to create runtimes or reuse them.
