### ISSUE TITLE
Possibility to retain the YAML `---` heading?

### ISSUE THREAD

**Issue by hawkrives** [mitsuhiko/insta#22]
Hi! Thanks for making Insta! It's really neat!

I find myself with a lot of snapshots of the following form:

```rust
  assert_yaml_snapshot_matches!(data, @r###"given: courses
what: courses
limit: []
where: {}
do:
  lhs: Count
  op: GreaterThan
  rhs:
    Integer: 2"###);
```

It's kinda awkward, having the first key be on the first line instead of lined up with the rest of the YAML.

It would be nice if we could retain the leading `---`, so as to achieve something like this:

```rust
  assert_yaml_snapshot_matches!(data, @r###"---
given: courses
what: courses
limit: []
where: {}
do:
  lhs: Count
  op: GreaterThan
  rhs:
    Integer: 2"###);
```

It looks like the `---` is stripped off here:

https://github.com/mitsuhiko/insta/blob/7d56a5cef1faa8fa7c681cdfd7f9c7368fa3c16c/src/serialization.rs#L18

Would you be willing to reconsider the stripping, or to bikeshed an option name?

Thanks again for making Insta!

**Comment by mitsuhiko** [comment]
I think retaining it for inline snapshots is reasonable, for external snapshots its annoying because we already use a separator for the header separation.

**Comment by hawkrives** [comment]
Agreed!

**Comment by mitsuhiko** [comment]
I have little time on my hand atm for this but if you could make a PR I can pull it.

**Comment by hawkrives** [comment]
I will give it a shot tonight, I hope, and report back!
