### ISSUE TITLE
Suggest `cargo insta test` when running `cargo test`

### ISSUE THREAD

**Issue by max-sixty** [mitsuhiko/insta#223]
We're using insta a lot in PRQL. 

A core dev wanted to split up the tests, because they were finding only the first test was replaced https://github.com/max-sixty/prql/pull/261. They had been running `cargo test` rather than `cargo insta test`.

Would it be helpful to add a comment to the "To update snapshots run `cargo insta review`" message that's printed to also say something like "Stopped on the first failure in {func}. Run `cargo insta test` to run all snapshots."

I can also write a "Contributing" guide which includes this for PRQL, but even better if it's upstreamed.

I'm happy to do a PR.

**Comment by mitsuhiko** [comment]
Fixed in d80987db6dcda1869f22f09b36f2bdea77fec25e. Good idea thanks!

**Comment by max-sixty** [comment]
Thanks a lot @mitsuhiko !
