### ISSUE TITLE
assert_snapshot get a error by 🫗

### ISSUE THREAD

**Issue by huang12zheng** [mitsuhiko/insta#234]
### What happened?

* input 1
insta::assert_snapshot!("🫗", "🫗");

```
Source: spec/tests/gvk.rs:84
+new results
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
"🫗"
────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
          0 │+🫗
────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
thread 'test2_proptest::proptest_gvk_case2' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 92, kind: Uncategorized, message: "Illegal byte sequence" }', spec/tests/gvk.rs:84:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test2_proptest::proptest_gvk_case2

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.14s
```

* input 2
you can copy 🫗 to Mac's Launchpad ,to find out what it is.

### Reproduction steps

https://github.com/huang12zheng/insta_issue
cargo test

### Insta Version

1.15.0

### rustc Version

rustc 1.61.0 (fe5b13d68 2022-05-18)

### What did you expect?

pass test

or

how to solve error

**Comment by mitsuhiko** [comment]
I believe you were trying to make an inline snapshot but instead provided a snapshot name. I assume you wanted this instead?

```rust
 insta::assert_snapshot!("🫗", @"🫗");
 ```

(note the trailing `@` on the snapshot value).

**Comment by huang12zheng** [comment]
thanks, 
Because I thought that just like assert_eq,
I was using propTest when the problem occurred
~~insta::assert_snapshot!( format!("{:?}", kube_gvk),format!("{:?}",gvk));~~
assert_eq!(format!("{:?}", kube_gvk),format!("{:?}",gvk));
