### ISSUE TITLE
Incompatible with nextest

### ISSUE THREAD

**Issue by untitaker** [mitsuhiko/insta#242]
### What happened?

with [nextest](https://nexte.st/), `cargo insta approve` only writes back changes for a single test. the repro steps have to be repeated 8-9 times until all dirty changes disappear from the git repo.

presumably because nextest runs each test in its own process and `pending-snaps` gets overwritten by each process.

### Reproduction steps

1. check out https://github.com/untitaker/quickenv
2. change all snapshots in `tests/acceptance.rs` by a character or so
3. `INSTA_FORCE_PASS=1 cargo nextest run`
4. `cargo insta approve`

### Insta Version

1.15.0

### rustc Version

rustc 1.64.0-nightly

### What did you expect?

one invocation of `cargo insta approve` should've captured all snapshot changes from all tests and approven them at once, undoing all uncommitted changes.

---

I wonder if `.pending-snaps` could:

1. become append-only (i.e. insta acquires a file lock and appends instead of overwriting file)
2. each entry contain hash of old/new snapshot content, so `insta approve` knows whether a "pending snap" is still relevant or can be skipped

**Comment by indietyp** [comment]
I'd love to get this fixed. Most of my tests use `nextest`, which makes this a huge pain to deal with.
