### ISSUE TITLE
Potential JSON serialization regression in 1.18.0

### ISSUE THREAD

**Issue by amy-keibler** [mitsuhiko/insta#270]
### What happened?

Thanks for developing such a useful snapshot testing library. I'm using it in a CycloneDX SBOM library. I received a [dependabot PR](https://github.com/CycloneDX/cyclonedx-rust-cargo/pull/218) to bump the version to the `1.18.0` version, but that had failing tests. When I investigated, I noticed that the JSON serialization output regressed, causing tests to fail. I assume it's related to the dependency changes and is likely caused by a bug in an upstream library, but I figured I should bring it to your attention, given its impact on the snapshot output.

The short description is that it seems like pretty-printed JSON is sometimes moved to the same line as the opening `{`, as shown in the snapshot output for the reproduction repository

```
❯ less src/snapshots/example_insta_regression__tests__serializes_to_json_correctly.snap.new 
---
source: src/lib.rs
assertion_line: 22
expression: "vec![Example :: ChoiceA(ChoiceAStruct { field_a : \"a\".to_string() }), Example\n    :: ChoiceB(\"b\".to_string()),]"
---
[
  {"choiceA": {
      "fieldA": "a"
    }
  },
  {"choiceB": "b"
  }
]
```

### Reproduction steps

I created an [example repository](https://github.com/amy-keibler/example-insta-regression) to demonstrate the issue. There is a PR open https://github.com/amy-keibler/example-insta-regression/pull/1 with failing tests that demonstrate the issue in CI

1. Clone the linked repository
   - Observe that that the version of `insta` is `~1.17.1` in the `main` branch
2. Run tests via `cargo test` and observe that they are passing
3. Checkout the `dependency-upgrade` branch
   - Observe that the version of `insta` is `1.18.0`
4. Run tests via `cargo test` and observe that they are failing with the following output
   ```
   ...
   -old snapshot
   +new results
   ────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       0     0 │ [
       1       │-  {
       2       │-    "choiceA": {
             1 │+  {"choiceA": {
       3     2 │       "fieldA": "a"
       4     3 │     }
       5     4 │   },
       6       │-  {
       7       │-    "choiceB": "b"
             5 │+  {"choiceB": "b"
       8     6 │   }
       9     7 │ ]
   ────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

   ...
   ```

### Insta Version

1.18.0

**Comment by mitsuhiko** [comment]
This is indeed a regression with newtype structs. Thanks for the report. I will prepare a bugfix release for this.

**Comment by mitsuhiko** [comment]
Pushed out `1.18.1` which fixes this. Thanks for the report!
