### ISSUE TITLE
Add tool config

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/insta#282]
With requests like #278 and my desire to make `cargo-insta test` support [nextest](https://nextest/) it might be time to introduce a config file. A potential location could be `workspace-root/.config/cargo-insta.yaml` or potentially even `insta.yaml` if that config file should be used for insta.

Some of the options to consider would be:

* Use `--accept-unseen` to be a default
* Use `--review` by default
* Enable snapshot compression
* Switch between `cargo test` and `cargo nextest` as default

**Comment by repi** [comment]
support for `cargo nextest` through config (or env var?) would be lovely, we generally use it for our tests in our large repo as is massively faster but do want to be able to run it with `cargo insta --review` for fast update and review of snapshots.

**Comment by mitsuhiko** [comment]
Yap. I absolutely want to get this in. I'm using it myself now quite a bit too.

**Comment by mitsuhiko** [comment]
The tool config is in, the remaining tasks are tracked as part of #323
