### ISSUE TITLE
feature request: allow optional trailing format string comment

### ISSUE THREAD

**Issue by scooter-dangle** [mitsuhiko/insta#286]
In several projects I work on that use insta, there are some cases where we could provide guidance to the dev running the tests what they should consider an acceptable change in the snapshot. E.g., in one project where we use `insta` as a simple verification tool that only new versions of a source doc are created, an acceptable change to the snapshot would be an additional entry in the vector of hashed source docs but not a change to an existing entry (at least wrt `main`).

Many assertions elsewhere in the ecosystem allow an optional tail of format string + args. E.g., [`debug_assert!`](https://doc.rust-lang.org/std/macro.debug_assert.html):

```rust
let a = 3;
let b = 27;
debug_assert!(a + b == 30, "a = {}, b = {}", a, b);
// Note: I'd also expect to be able to do the following
debug_assert!(a + b == 30, "a = {a}, b = {b}");
```

We currently have something like the following:

```rust
    // Only accept a change that adds a revision to hashed_docs unless you're
    // deprecating an epoch of revisions.
    insta::assert_snapshot!(serde_json::to_string_pretty(&hashed_docs).unwrap());
```

A dev only sees `serde_json::to_string_pretty(&hashed_docs).unwrap()` in the insta review and needs to go check the source for the guidance (assuming they know that such guidance will be there). It would be helpful if we could instead write

```rust
    insta::assert_snapshot!(
        serde_json::to_string_pretty(&hashed_docs).unwrap(),
        "Only accept a change that adds a revision to hashed_docs unless you're \
        deprecating an epoch of revisions.",
    );
```

and have that message (again, possibly with format args, though they aren't needed in this example) included with the snapshot review diff.

**Comment by mitsuhiko** [comment]
You can accomplish something like this by using the `description` field which is shown in the review tool:

```rust
insta::with_settings!({
    description => "Only accept a change that adds a revision to hashed_docs unless you're deprecating an epoch of revisions"
}, {
    insta::assert_snapshot!(
        serde_json::to_string_pretty(&hashed_docs).unwrap()
    );
});
```

Now might not have the most convenient syntax but you could experiment with creating a utility macro around it, that helps with that. Additionally maybe you can also use a utility function that creates and binds changed settings.

**Comment by scooter-dangle** [comment]
Thanks, @mitsuhiko! Apologies for not finding it myself. I had looked through the macro declarations for anything resembling a description. I saw that there _were_ settings but hadn't thought to look there.
