### ISSUE TITLE
JSON serialization changed for `serde_json::value::RawValue`

### ISSUE THREAD

**Issue by psFried** [mitsuhiko/insta#290]
### What happened?

We have some snapshot tests using some structs that include `serde_json::value::RawValue` fields. These tests started failing after upgrading from insta version `0.14.0` to `0.20.0`. Here's an example of the diffs:

```
   43    43 │           "image": "ghcr.io/foo/bar/source-potato:v1.2.3",
   44       │-          "config": {"some":"config"}
         44 │+          "config": {
         45 │+            "$serde_json::private::RawValue": "{\"some\":\"config\"}"
         46 │+          }
   45    47 │         }
   46    48 │       },
   47    49 │       "bindings": [
```

### Reproduction steps

1. Use `insta::assert_json_snapshot(MyStructWithRawValueField);` with `insta:1.14.0` and commit the snapshot.
2. Upgrade insta dependency
3. Observe failing test

### Insta Version

1.14.0 -> 1.20.0

### rustc Version

1.64

### What did you expect?

I'm not entirely sure what the expected behavior should be here. The new representation actually seems reasonable from the standpoint that equality of a `RawValue` perhaps out to depend on the actual string representation rather than just the values of the parsed JSON. In other words, the new format causes semantically insignificant differences in the `RawValue`-wrapped JSON (such as whitespace) to be considered significant when comparing snapshots.

What do you think? Should this be considered a regression or a feature?

**Comment by mitsuhiko** [comment]
Ah interesting. Serde's in-band signalling strikes again (https://github.com/serde-rs/serde/issues/1463). I did not expect this but now that it happened I would probably prefer to keep it this way.

I believe fundamentally serde needs to find a better way to represent these things and I probably don't want to hack this into this library now to match the behavior.

**Comment by psFried** [comment]
Makes sense. I'll consider it a 'happy accident' :grin:  Thanks for the quick reply.
