### ISSUE TITLE
Consider `--all` by default

### ISSUE THREAD

**Issue by matklad** [mitsuhiko/insta#30]
Currently `cargo insta` in workspace prints

>error: Cargo.toml appears to be a workspace root but not a package by itself.  Enter a package folder explicitly or use --all

I wonder if it could just work as if `--all` was there?

I believe currently Cargo ~~works this way~~ uses implied `--all` as well, although it used to emit the similar "hey, rerun me with --all" kind of error.

**Comment by mitsuhiko** [comment]
We match the behavior of cargo as far as I know. Typically the workspace root is a crate and not crateless. If `--all` were implied you could not test the root crate in isolation.

**Comment by matklad** [comment]
Ah, in my case workspace root is a virtual manifest, and, for *virtual* manifests, all is implied: https://github.com/rust-lang/cargo/issues/4021

Even more specifically, virtual manifest can specify a list of `default_members`, which defaults to all ws crates, and commands without `-p` / `--all`, operate on that.

https://doc.rust-lang.org/cargo/reference/manifest.html#package-selection

**Comment by mitsuhiko** [comment]
I would accept a patch for that.

**Comment by brendanzab** [comment]
Yeah, I'm in a similar boat here! I often use virtual manifests and the `--all` behaviour is a tad irritating.
