### ISSUE TITLE
Better UX for snapshots containing ANSI escape sequences

### ISSUE THREAD

**Issue by CobaltCause** [mitsuhiko/insta#300]
I have a command line tool I'm using insta to test, and right now I'm using the `strip-ansi-escapes` crate to... strip the ansi escapes before they get to insta to make snapshot diffs readable. Without stripping ansi escapes, the review TUI looks like this, for example:

![image](https://user-images.githubusercontent.com/7003738/200960795-f4d5f613-2883-4dd1-8179-cb7932abb191.png)

When the actual output is supposed to look like this:

![image](https://user-images.githubusercontent.com/7003738/200961000-217cb564-2862-4ce6-893e-67f2cbe42e8d.png)

Using insta to test the CLI output without colors has still been incredibly helpful, but it would be even better if I could make sure my color output works like I want it to as well.

Unfortunately, I don't have any great ideas on how to actually deal with this, though. Maybe some sort of argument to the `insta::assert_display_snapshot` macro that causes the TUI to not draw effects on the changed text itself but only leaves the `-`s and `+`s around?

**Comment by mitsuhiko** [comment]
My hunch is that the most correct thing here would be to actually strip ANSI codes before rendering. Probably also makes sense to start rendering newlines when needed like [`similar-asserts`](https://docs.rs/similar-asserts/) already does.
