### ISSUE TITLE
`cargo insta test -- --lib` no longer works in `1.21.1`

### ISSUE THREAD

**Issue by max-sixty** [mitsuhiko/insta#301]
### What happened?

Hope all's well @mitsuhiko ! I can look more into this but if you recognize it immediately, let me know.

In 1.21.1, this no longer works:

```sh
$ cargo insta test -- --lib

    Finished test [unoptimized + debuginfo] target(s) in 0.15s
     Running unittests src/main.rs (target/debug/deps/mdbook_prql-164cd20fe335a310)
error: Unrecognized option: 'lib'
     Running tests/snapshot.rs (target/debug/deps/snapshot-5d4066602c4c92c1)
error: Unrecognized option: 'lib'
     Running unittests src/lib.rs (target/debug/deps/prql_compiler-e4c606bb74a69d65)
error: Unrecognized option: 'lib'
```

Nor does:

```sh
cargo insta test -- -p prql-compiler
```

(though because `cargo insta` support `-p` natively, this one doesn't matter so much)

I'm guessing it's related to https://github.com/mitsuhiko/insta/commit/b85e89a39cfd9713d8d13aa8cfb4eb99fed6bd10

Thank you as ever!

### Reproduction steps

I'm trying on https://github.com/prql/prql, though I guess it's generally applicable.

And here's a repro in GHA of a longer command (this used to pass) https://github.com/prql/prql/actions/runs/3485604228/jobs/5831288796#step:7:136

### Insta Version

1.21.1

### rustc Version

rustc 1.64.0 (a55dd71d5 2022-09-19)

**Comment by mitsuhiko** [comment]
This is quite annoying. Turns out that we basically need to support both but it's unclear how to best accomplish this. Kinda want to redo this entire feature.
