### ISSUE TITLE
Unreliable debug implementation between stable and nightly rust

### ISSUE THREAD

**Issue by irevoire** [mitsuhiko/insta#303]
Hey, we had a funny issue while using insta; I don't think it's on your side or that you should do something about it, but it's probably a good idea to bring it to your attention.

The debug implementation of the `PhantomData` isn't the same between rust-stable and rust-nightly, which can cause hard-to-understand issues.

**Comment by mitsuhiko** [comment]
Unfortunately `Debug` is notoriously stupid for snapshot testing which is why my recommendation is to use one of the serde based formats instead. An alternative I could offer in this case would be to register a filter:

```rust
insta::with_settings!({filters => vec![
    (r"\bPhantomData<.*>([,\r\n])?", "PhantomData$1"),
]}, {
    insta::assert_snapshot!(...);
});
```
