### ISSUE TITLE
Provide non-assert variant

### ISSUE THREAD

**Issue by CAD97** [mitsuhiko/insta#31]
I'm writing a test harness using insta that does test case discovery itself. It would be great if you could expose a `Result`-giving API (roughly `runtime::assert_snapshot`?) to allow usecases like this to have a bit more control.

**Comment by mitsuhiko** [comment]
Can you be more specific about what you are looking for?

**Comment by CAD97** [comment]
What I'm trying to do:

Have a single test runner that uses rayon to spin up a work pool that uses insta to snapshot test a processing of files in a directory. More specifically, parse every file in a directory with gll and assert that the debug representation of the resulting forest is unchanged. Because `assert_snapshot_matches` prints to stderr and panics, I have to create a new thread for each test, allow the threads to panic, and run the tests serially so that stderr is not interleaved.

How I think it could be accomplished:

insta provides a `fn snapshot_matches(name: &str, snapshot: &str) -> Result<(), impl Display>` where the `Display` impl is the currently dumped stderr.

**Comment by CAD97** [comment]
Another option would be for insta to provide this harness itself. I find this to be a common desire for parsing projects at least, so it wouldn't be unwarranted to provide.

The API would be something like:

```rust
insta::snapshots_match_in!(
    directory: AsRef<Path>, // the directory to search
    ext: &str; // the file extension to process (optional, omit == all)
    transform: impl Fn(&str) -> impl AsRef<str>
);
insta::yaml_snapshots_match_in!(
    directory: AsRef<Path>, // the directory to search
    ext: &str; // the file extension to process (optional, omit == all)
    transform: impl Fn(&str) -> impl Serialize,
    { redactions } // (optional)
)
```

and so on. This would run snapshots by reading every file in the given directory (recursively?) (optionally with the given extension), passing them through the transform, checking the snapshot, and collecting all of the results. All of the tests would always be run, it wouldn't short-circuit at the first. The best bet for iterating over test files like this is probably `WalkDir` into `rayon::ParBridge`.

(Bonus points if we can increase the stack size of runner; the wg-grammar use case currently requires a larger stack to print out the gll tree's debug representation.)

If you OK a general direction and point at where the snapshot failure panic is currently invoked, I could take a poke at implementing this.

**Comment by mitsuhiko** [comment]
Yeah, that sounds like something that could be useful. The panic handling is all in `runtime.rs`.

**Comment by mitsuhiko** [comment]
More specifically here: https://github.com/mitsuhiko/insta/blob/8a8e3ee8826d0129927c6c394b7043d8f421899c/src/runtime.rs#L555-L562

**Comment by CAD97** [comment]
Closing this for more directed issue.
