### ISSUE TITLE
Make insta use different messages for missing snapshot

### ISSUE THREAD

**Issue by lu-zero** [mitsuhiko/insta#315]
We are trying to debug why a setup that keeps the tests in a separate repository is failing only on the CI system and not locally and insta is not helping figure out why the test fails.

**Comment by mitsuhiko** [comment]
I am not sure what the ask is here exactly. Can you elaborate?

**Comment by lu-zero** [comment]
I'm trying to figure out why some test fails only on CI and not locally on multiple machines and it would had been helpful to see if the problem were that the snapshots were missing or changed. 

Probably I should start sending you patches and make so cargo-insta produces a report that can be consumed further :)

Apparently the problem is in the precision of the float representation and curiously it hits also yaml.

**Comment by mitsuhiko** [comment]
If a snapshot is new it already shows up in the review output as new.

**Comment by lu-zero** [comment]
Only if you add `--nocapture`, but I guess it is good enough. 

So far switching to insta already helped to find at least 3 different issues :)

**Comment by mitsuhiko** [comment]
That should not be necessary. I'm curious as of why that is needed.

**Comment by lu-zero** [comment]
Without --nocapture I [see](https://community-tc.services.mozilla.com/tasks/ZLigwJksQ9ybjk3s_flR1A/runs/0/logs/public/logs/live.log#L1181):
```
stored new snapshot C:\Users\task_167120363099675\rust-code-analysis\tests\repositories\rca-output\snapshots\serde\serde\src\de\test__impls.rs.snap.new
```
with --nocapture I see the [diff](https://community-tc.services.mozilla.com/tasks/AB_iHgjCQvKFsaMLn2nGeQ/runs/0/logs/public/logs/live.log).

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Differences ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: tests\repositories\rca-output\snapshots\serde\serde\src\de\test__impls.rs.snap
Snapshot: impls.rs
Source: C:\Users\task_167120363099675\rust-code-analysis:54
───────────────────────────────────────────────────────────────────────────────
Expression: funcspace_struct
───────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬──────────────────────────────────────────────────────────────────
20334 20334 │                 ploc_min: 1,
20335 20335 │                 ploc_max: 75,
...
```

**Comment by mitsuhiko** [comment]
Does your CI not set the `CI` environment variable?

**Comment by lu-zero** [comment]
Probably not. I guess that explains :)

**Comment by mitsuhiko** [comment]
Please try. That should improve your experience.

**Comment by lu-zero** [comment]
Thank you :)

**Comment by mitsuhiko** [comment]
I will close this then.
