### ISSUE TITLE
Option to raise on unreferenced snapshots?

### ISSUE THREAD

**Issue by max-sixty** [mitsuhiko/insta#321]
(I realize I've been putting in more issues than I've been fixing, but here is another)

We have `--delete-unreferenced-snapshots`, but in CI we often want to raise on unreferenced snapshots, (e.g. https://github.com/charliermarsh/ruff/pull/1525, and I was about to add the same for PRQL, and then though of this idea)

How about instead of `--delete-unreferenced-snapshots`:
- We have a flag like `--include-unreferenced`
- When passed, we take the value of `INSTA_UPDATE` for unreferenced snapshots too, whose default is "`no` for CI environments or `new` otherwise"
- Then we get the same behavior as `--delete-unreferenced-snapshots` locally — since we're resetting them to their correct state by deleting them, and we raise in CI — since they're not in their correct state.

An alternative approach would just be another flag like `--raise-on-unreferenced`, though that seems less orthogonal.

**Comment by mitsuhiko** [comment]
I wonder if the less magical behavior would be a new flag called `--unreferenced` with the following options:

* `--unreferenced=reject`: fail with an error if there are unreferenced left
* `--unreferenced=delete`: automatically delete unreferenced files
* `--unreferenced=auto`: runs `delete` locally and `reject` in CI
* `--unreferenced=warn`: emits a warning on unreferenced snapshots
* `--unreferenced=ignore`: ignore unreferenced snapshots

I believe a sensible default going forward then might be `warn`. With the new tool config that default could be changed.

**Comment by max-sixty** [comment]
Super!

(I had been trying to collapse the config into the existing `INSTA_UPDATE` items by adding a single flag to consider unreferenced snapshots, rather than a new dimension of configs, but I agree it's not a perfect abstraction)

> I believe a sensible default going forward then might be `warn`. With the new tool config that default could be changed.

As one data point, PRQL can't run all its snapshot tests with every target, so we would not want `warn`, in an effort to reduce spurious warnings. (Even aside from us sometimes running a subset of tests). Though for smaller projects with a single target it's probably correct.

Thank you v much as ever @mitsuhiko !

**Comment by mitsuhiko** [comment]
I will leave the default with `ignore` for now and then see later. The tool config can now be used anyways to influence this.
