### ISSUE TITLE
Using new config file for ignoring & force update

### ISSUE THREAD

**Issue by max-sixty** [mitsuhiko/insta#329]
### What happened?

I'm not sure if I'm making a basic mistake here, but thought it would be helpful on the margin to report this in case I'm not:

I have the following config file at `insta.yaml`:

```yaml
behavior:
  force_update: true
review:
  include_ignored: false
  include_hidden: false
```

But running:

```sh
cargo insta test -p prql-compiler --lib
```

- Doesn't force update snapshots. Running with `--force-update-snapshots` makes a change that the previous command had not made
- Displays a warning `warning: some paths are not picked up by cargo insta, use --include-ignored and --include-hidden if you have snapshots in ignored or hidden paths.`. Possibly those configs only work under `review:`?

I confirmed that the config file is getting read (if I make it an invalid YAML file, `cargo insta` fails)

### Insta Version

1.24

### rustc Version

rustc 1.65.0 (897e37553 2022-11-02)

**Comment by mitsuhiko** [comment]
`include_ignored` and `include_hidden` are already set to `false` by default so that won't do anything. I'm not sure why `force_update` wouldn't be honored however. I ran that against insta itself just now and it updates properly. Any chance this is running an old version of `cargo-insta`? Though that flag is picked up by insta itself so not sure why that would break anything.

**Comment by ngryman** [comment]
It seems to be a broader issue, `review.include_ignored: true` is also not honored (re #326).

![image](https://user-images.githubusercontent.com/892048/210538525-5ef746a9-0269-4fa1-88a2-ae2cdf5e2d54.png)

**Comment by max-sixty** [comment]
Sorry, I think `cargo-insta` was updated but `insta` in the repo wasn't. `force-update` does work now that both have been updated.

> `include_ignored` and `include_hidden` are already set to `false` by default so that won't do anything.

Yes, makes sense. Is there any way to disable the warning when running tests? That has returned.

(OK if the answer is — "it could be if you want to do a proper contribution"!)

**Comment by mitsuhiko** [comment]
I'm going to revisit this warning now. There should be a better way to accomplish this.

**Comment by max-sixty** [comment]
Thanks @mitsuhiko ! Closing this as completed by #334. Very grateful for all your work on this!
