### ISSUE TITLE
Consider not looking at the macro name in cargo-insta

### ISSUE THREAD

**Issue by dtolnay** [mitsuhiko/insta#33]
Currently `cargo insta review` will only update @​r###"..."### if it is contained inside of a macro invocation whose name starts with `assert_` and ends with `_snapshot_matches`.

https://github.com/mitsuhiko/insta/blob/ed562d33a0a5a1ccb4bbee02c36e09835a1ca1fe/cargo-insta/src/inline.rs#L141-L144

That forces the same naming convention on helper macros that the calling code might want to use. For example in Syn it would be convenient to use a macro that parses tokens to syntax tree, compares against an inline snapshot, and evaluates to the parsed syntax tree as an expression in case the caller wants to do further assertions on it.

Would you foresee any problems with skipping the name check entirely and relying on finding a macro with any name spanning the right lines and with its input tokens ending in @​r###"..."### ?

**Comment by dtolnay** [comment]
(Mentioning @mitsuhiko since you're not watching the repo -- sorry if that's on purpose!)

**Comment by mitsuhiko** [comment]
We would have to force `r"""` to be used consistently. Right now this is only enforced if the string is containing quotes or newlines. One option would be to have a config file to add extra patterns in, the other would be to just see what happens if that restriction is lifted. The `@` marker might be a good enough indication maybe.

**Comment by dtolnay** [comment]
Are there any situations where it would go wrong other than two macro invocations on the same line?

```rust
#[test]
fn test() {
    insta_assertion_helper!(..., @""); not_insta_but_coincidentally_looks_like_it!(..., @"");
}
```

If it's pick-two-out-of-three among the following:

1. Support helper macros with any name
2. Support multiple invocations on the same line
3. No config file

then multiple invocations on the same line would be the least important to me.
