### ISSUE TITLE
Improve test coverage of behavior flags

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/insta#332]
Insta and cargo-insta currently have very limited coverage for behavioral flags which makes it easy to accidentally regress. This relies on manual testing at the moment.

Refs #331, #326, #330, #329.

**Comment by max-sixty** [comment]
The structure is at least set up in https://github.com/mitsuhiko/insta/blob/71f771300b256c62cb34828658457c48ad6e018d/cargo-insta/tests/main.rs now. Some but not all are tested, and when I fix a bug I add a test. So will close this as completed.
