### ISSUE TITLE
Only print updated files on `force_update`

### ISSUE THREAD

**Issue by max-sixty** [mitsuhiko/insta#333]
(caveat: this is not _that_ important, and I'm open to the feedback that it's not worth adding an issue over, or that I should do a PR instead of adding more issues)

Now that we have a config file, and since snapshots no longer have line references, I'm keen to have `force_update` be true in PRQL. Mostly it'll be updating when the expression changes, which we want.

But currently the output is very noisy — it prints a line for every snapshot, whether or not it's updated. We have hundreds of snapshots, so it makes for a very noisy terminal output.

If it could only print when it makes a change, this would be a much clearer output.

**Comment by mitsuhiko** [comment]
Not only does it print needlessly, it also produces a completely pointless `.new` file which brings up an empty review dialog. Really should be improved.
