### ISSUE TITLE
Using insta in doctest

### ISSUE THREAD

**Issue by irevoire** [mitsuhiko/insta#339]
Hey, I was playing with insta and tried to use it on my doctest.
I noticed it was able to emit diffs but not apply them, is this expected?
Is that something insta could support?

-----

EDIT: Just realised there was a warning indicating that this feature is not supported.
It would be nice tho'

**Comment by mitsuhiko** [comment]
I would love to support it but unfortunately the line information emitted by rustc is wrong. I believe this issue tracks this: https://github.com/rust-lang/rust/issues/79417

**Comment by max-sixty** [comment]
Will plan to close as waiting on rustc
