### ISSUE TITLE
`cargo-insta` does not detect CI

### ISSUE THREAD

**Issue by not-my-profile** [mitsuhiko/insta#344]
For our CI at [ruff](https://github.com/charliermarsh/ruff), we'd like to use `cargo test` instead of `cargo insta test` since the former prints diffs for failing snapshots, while the latter just prints "use `cargo insta review` to review snapshots" ... which of course doesn't work in the CI.

Switching to `cargo test` would however mean we'd no longer test for unreferenced snapshot files ... so perhaps `cargo insta` could introduce a new subcommand to only test for unreferenced snapshot files without running the tests ... e.g. `cargo insta check-snapshots <value>` where value could be the same values that the `--unreferenced` option of `cargo insta test` accepts ... or perhaps rather a `cargo insta test` flag to skip the running of the tests?

What do you think about that?

**Comment by not-my-profile** [comment]
Oh ok ... I didn't know that insta had CI detection.

I have now done a test commit to debug this and I am very confused ... see [this GitHub workflow log](https://github.com/charliermarsh/ruff/actions/runs/4067610657/jobs/7005160476). According to `env` the `CI=true` environment variable is set ... but `cargo insta test` still doesn't show the diff.

**Comment by mitsuhiko** [comment]
Interesting. I will debug this. Normally the snapshot update behavior would be set to `auto` which should detect ci:

https://github.com/mitsuhiko/insta/blob/7c098225b630d583fd1216b18d2e126739940e0e/src/env.rs#L324-L330

Do you have a config file t

**Comment by mitsuhiko** [comment]
This is definitely a bug in `cargo-insta`. I will fix this. It overrides this flag.
