### ISSUE TITLE
Removal of `Settings::bind_to_thread` violates semver

### ISSUE THREAD

**Issue by PatchMixolydic** [mitsuhiko/insta#352]
### What happened?

I took a dependency on `insta` back when 1.14 was the latest version:
```toml
[dependencies]
insta = "1.14.0"
```

Today, I ran `cargo update`, which updated the locked version of `insta` to 1.28:
```diff
  name = "insta"
- version = "1.14.0"
+ version = "1.28.0"
```

However, this caused my crate's snapshot test harness to break due to [the removal of `Settings::bind_to_thread`](https://github.com/mitsuhiko/insta/blob/master/CHANGELOG.md#1180):
```
   Compiling laria v0.1.0 (/home/patchmixolydic/Programming/Rust/laria/laria)
error[E0599]: no method named `bind_to_thread` found for struct `Settings` in the current scope
  --> laria/tests/ui.rs:19:14
   |
19 |     settings.bind_to_thread();
   |              ^^^^^^^^^^^^^^ method not found in `Settings`

error[E0599]: no method named `bind_to_thread` found for struct `Settings` in the current scope
  --> laria/tests/ui.rs:26:26
   |
26 |                 settings.bind_to_thread();
   |                          ^^^^^^^^^^^^^^ method not found in `Settings`

For more information about this error, try `rustc --explain E0599`
```

### Reproduction steps

1. Checkout [PatchMixolydic/laria at `5f82065bd1`](https://github.com/PatchMixolydic/laria/tree/5f82065bd187b2f553645142085ca664ff88fe11).
2. Run `cargo test`.
3. Run `cargo update`.
4. Try to run `cargo test` again.

### Insta Version

1.14 → 1.28

### rustc Version

rustc 1.69.0-nightly (0416b1a6f 2023-02-14)

### What did you expect?

Per [Cargo's documentation on semver compatibility](https://doc.rust-lang.org/cargo/reference/semver.html#change-categories), the removal of `Settings::bind_to_thread` should've resulted in a bump to the major version, which would have prevented this scenario altogether.

**Comment by mitsuhiko** [comment]
That's a fair callout. It has been removed from the library for quite a while now at this point which is why I don't think there is much point in bringing it back as deprecated method.

**Comment by PatchMixolydic** [comment]
Thank you for the quick response! Given the circumstances, it does seem like reintroducing the method wouldn't be worth the extra maintenance burden at this point, so I'll go ahead and close this issue.
