### ISSUE TITLE
Support serializers for images

### ISSUE THREAD

**Issue by cjhowedev** [mitsuhiko/insta#355]
This aids in building snapshot tests of UIs based on screenshot images of the window. Could be used for testing websites, mobile apps, desktop apps, games, or even headless image manipulation.

We could support generating diff images when snapshot tests fail, report additional metrics such as the percentage difference between the image, and implement a threshold that allows for small differences to not fail tests.

**Comment by mitsuhiko** [comment]
Relates to #196

**Comment by max-sixty** [comment]
Closed by #610
