### ISSUE TITLE
Add support for `test.delete_unreferenced_snapshots`

### ISSUE THREAD

**Issue by Pegasust** [mitsuhiko/insta#356]
Either add it to the [documented list of settings](https://insta.rs/docs/settings/#tool-config-file), or add support for such setting.

**Comment by max-sixty** [comment]
Is the `behavior.update` config in the config file sufficient? https://insta.rs/docs/settings/#tool-config-file

**Comment by Pegasust** [comment]
Thanks! I can confirm that this is the expected behavior!

Would be great if we can add some mappings of these rules from the CLI to the config file 😀

**Comment by max-sixty** [comment]
On reflection, I'm actually not sure having a `delete_unreferenced_snapshots` in a config file would make sense — it would mean that running any subset of tests would delete all other snapshots.

And IIUC it's not possible to know whether we're running a subset of tests...

**Comment by Pegasust** [comment]
Closing this since I agree that we should probably just `cargo insta test --unreferenced=delete`. This is to ensure that unreferenced snapshots are deleted only in "global run". 
I would just resort to aliasing the command on the shell of choice to make this less verbose.
Thanks for the clarification on the config file options!
