### ISSUE TITLE
[Regression] "Unrecognized option" when passing in workspace and exclude

### ISSUE THREAD

**Issue by GeeWee** [mitsuhiko/insta#359]
### Description

I used to run the following `cargo-insta` command reasonably often.

`cargo insta test -- --workspace --exclude integration-tests`

Aka, run insta tests on the entire workspace except for one crate.
I recently updated `cargo-insta`, and it no longer works. Unfortunately I didn't track which version I updated to/from.
I now get some variation of the following error for all my crates:
```
error: Unrecognized option: 'workspace'
error: test failed, to rerun pass `-p api_errors --lib`
     Running unittests src/lib.rs (target/debug/deps/classification-6fee9f50272217d2)
error: Unrecognized option: 'workspace'
error: test failed, to rerun pass `-p classification --lib`
     Running unittests src/lib.rs (target/debug/deps/classification_types-7efad87a3d24e667)
error: Unrecognized option: 'workspace'
```

I've confirmed that `cargo test --workspace --exclude integration-tests` works in the same repository. 

If I try to use the workspace property of `cargo-insta` instead, with a command like this: `cargo insta test --workspace -- --exclude integration-tests` - I get the following pretty similar errors
```
error: Unrecognized option: 'exclude'
error: test failed, to rerun pass `-p api_errors --lib`
     Running unittests src/lib.rs (target/debug/deps/classification-6fee9f50272217d2)
error: Unrecognized option: 'exclude'
error: test failed, to rerun pass `-p classification --lib`
     Running unittests src/lib.rs (target/debug/deps/classification_types-7efad87a3d24e667)
```

`cargo-insta` does not seem to have an `exclude`, so I can't pass it as  a top-level property.

So it seems like there's something that goes wrong when forwarding arguments to `cargo test`
Might be related to #301 

### Insta Version

cargo-insta 1.28.0

### rustc Version

rustc 1.68.0

**Comment by mitsuhiko** [comment]
The way `--` worked before was a bit buggy. The parameters are explicitly handled as part of `cargo insta test` now but unfortunately `--exclude` was omitted. I will fix this.

**Comment by mitsuhiko** [comment]
The way `--` worked before was a bit buggy. The parameters are explicitly handled as part of `cargo insta test` now but unfortunately `--exclude` was omitted. I will fix this.

**Comment by GeeWee** [comment]
Ah, that's awesome! Any chance we can get 1.29 released to crates.io so I can test it out?

**Comment by mitsuhiko** [comment]
Made a release.

**Comment by GeeWee** [comment]
Works like a charm! Thank you so much!
