### ISSUE TITLE
Allow passing `--profile`

### ISSUE THREAD

**Issue by max-sixty** [mitsuhiko/insta#381]
I know adding the standard cargo options has been a long tail. One that insta doesn't currently support is `--profile`:

These both fail:
```sh
cargo insta test --profile=dev
cargo insta test -- --profile=dev
```

(Probably it's too late now; would there be an option to forward options to cargo rather than trying to handle them as first-class options in insta? Possibly after a `--`, like `cargo insta test -- --profile=dev -- test_name`??)

**Comment by mitsuhiko** [comment]
I think at this point it's better to just suck it up and add them as they appear.

**Comment by tamird** [comment]
@mitsuhiko think you could cut a release with the fixes for this?

**Comment by mitsuhiko** [comment]
Yeah I will make one.
