### ISSUE TITLE
Settings::bind_to_scope can be misused accidentally

### ISSUE THREAD

**Issue by TheNeikos** [mitsuhiko/insta#383]
### What happened?

The guard of https://docs.rs/insta/latest/insta/struct.Settings.html#method.bind_to_scope can be insta-dropped when not binding it:

```
settings.bind_to_scope();
```

### Reproduction steps

1. Make a settings
2. Call bind_to_scope and not bind it
3. Settings wont go into effect

### Insta Version

1.29

### rustc Version

1.70

### What did you expect?

That settings get applied, or a warning/error.

One way of doing this is to have the `Guard` be `#[must_use = "An immediately dropped guard won't have any effect. Use `let _guard = ...` to bind it"]` which will at least warn users.

A showcase: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d3a996942ea918789b41805d7435de47

One issue is that the default help text says to use `let _ =` which is still wrong...

**Comment by mitsuhiko** [comment]
This change was made in 362eb95f13449d12554be7bfd300bc0a7f26f850
