### ISSUE TITLE
Make insta CLI work outside of cargo, and distribute it via npm

### ISSUE THREAD

**Issue by untitaker** [mitsuhiko/insta#387]
[sentry](https://github.com/getsentry/sentry) uses insta to review snapshot files generated by python code. There is an ad-hoc implementation of insta-the-library vendored somewhere in `sentry.utils.pytest.fixtures`.

People who want to review those snapshots currently have to install `insta` via cargo. What if insta used `cargo-dist` to distribute insta CLI on npm instead? Then sentry can add it to the developer's setup using `yarn add --dev`. Yes, as a frontend dev dependency, but everybody knows how to install those. Better would be pypi package, but who has time for that.

**Comment by untitaker** [comment]
fwiw i tried cargo-dist on another project and it isn't really hard to get it working for both npm + prebuilt binaries, can recommend

**Comment by mitsuhiko** [comment]
`cargo-insta` now has binaries. Closing this as resolved.
