### ISSUE TITLE
Support for serde arbitrary_precision

### ISSUE THREAD

**Issue by yanns** [mitsuhiko/insta#391]
### What happened?

The library does not seem to handle serde json number saved with arbitrary precision

### Reproduction steps

- When I enable the [feature `"arbitrary_precision"` from serdejson](https://github.com/serde-rs/json/blob/e98e664b42aceb245eaf801fc9ab726284693a68/Cargo.toml#L69C61-L75), 
- and when I use `insta::assert_json_snapshot!(<value>);`
- then the snapshots contain the following diff:
```
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    7     7 │     "typeId": "product",
    8     8 │     "id": "id",
    9     9 │     "obj": {
   10    10 │       "id": "id",
   11       │-      "version": 2,
         11 │+      "version": {
         12 │+        "$serde_json::private::Number": "2"
         13 │+      },
```

### Insta Version

2.0.1

### rustc Version

1.70.0

### What did you expect?

The diff should not happen

**Comment by yanns** [comment]
Update: the issue was coming from a custom deserializer.

**Comment by huuff** [comment]
Do you have any pointers on solving this? I'm using the `rust_decimal::serde::arbitrary_precision` module to serialize newtype around `rust_decimal::Decimal` as a number, and getting this issue. But I don't see how this could be solved, since the serializer itself is very simple
