### ISSUE TITLE
export redactions::Selector and Redaction

### ISSUE THREAD

**Issue by ajwerner** [mitsuhiko/insta#418]
When writing a dynamic redaction, it'd be nice to be able to leverage the existing selector and redaction logic to redact parts of a structure.

**Comment by mitsuhiko** [comment]
`Redaction` is already exported. I was hoping that `Selector` can stay internal and there is no use for it. Do you have an example of how you would use it?

**Comment by ajwerner** [comment]
I don't remember, so I'll close this. Sorry for the noise.
