### ISSUE TITLE
make redactions syntax support rustfmt

### ISSUE THREAD

**Issue by ajwerner** [mitsuhiko/insta#419]
Rustfmt will format macro invocations that are valid rust syntax. One approach that I'd support is to add a single syntax rule that puts `match redactions` in front of the redactions block.

**Comment by mitsuhiko** [comment]
Your suggestion is to allow instead of

```rust
insta::assert_yaml_snapshot!(..., {
    "selector" => replacement_value
});
```

The following syntax?

```rust
insta::assert_yaml_snapshot!(..., match redactions {
    "selector" => replacement_value
});
```

Or something like this?

**Comment by ajwerner** [comment]
Correct.
