### ISSUE TITLE
cargo metadata JSON output parsed as yaml

### ISSUE THREAD

**Issue by dspicher** [mitsuhiko/insta#462]
I am wondering why the output of `cargo metadata` [is parsed as yaml](https://github.com/mitsuhiko/insta/blob/3cb9934aa30d16ba0dc9355413a01d299e340015/src/env.rs#L397), whereas [it is documented](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html) to be JSON, which I reproduced locally, also with `--format-version=1` (`cargo 1.76.0 (c84b36747 2024-01-18)`).

The trigger for this question was that the dependency used to do the yaml parsing, `yaml-rust`, is since today [flagged as unmaintained](https://rustsec.org/advisories/RUSTSEC-2024-0320) by RUSTSEC. Without the above code, the `yaml-rust` dependency could be declared optional under the `yaml` feature.

**Comment by dspicher** [comment]
I would be happy to submit a PR that migrates to the recommended (`yaml-rust2`)[https://github.com/Ethiraric/yaml-rust2].

**Comment by max-sixty** [comment]
FYI the requirement for the yaml dependency comes from writing the snapshots as yaml

**Comment by dspicher** [comment]
> FYI the requirement for the yaml dependency comes from writing the snapshots as yaml

The above linked code location is the only one where `yaml-rust` is used for something else than writing yaml snapshots.

**Comment by mitsuhiko** [comment]
Closing this as non actionable. It's parsed as YAML as YAML is a superset of JSON and as such we avoid an extra dependency.

**Comment by dspicher** [comment]
> as YAML is a superset of JSON

I was not aware of that disturbing fact :+1:
