### ISSUE TITLE
Change from ⋮ to just white space?

### ISSUE THREAD

**Issue by max-sixty** [mitsuhiko/insta#47]
Would you take a PR to change the inline test indentation from using `⋮` to just removing the rectangle of white space, similar to https://github.com/janestreet/ppx_expect#whitespace?

I had started on that PR but thought it worth checking first...

**Comment by mitsuhiko** [comment]
I was thinking of this but this will make diffing much harder. We *could* do it in a way where the leading whitespace of a line is ignored but patched back on the diff.

So for instance the reference value is this:

```
    foo
      bar
```

And the comparison value is this:

```
  foo
  bar
```

In that case we could patch up the comparison value with all the leading whitespaces of the reference value before doing the diffing.

Otherwise I'm -1 on this change most likely because it will be confusing as hell.

**Comment by max-sixty** [comment]
Definitely not worth doing if it makes diffing harder. The intention was to reduce complication by removing the need for an unusual character and any mandate for a specific indentation. The way I'm thinking about it, it wouldn't make diffing harder (but maybe I'm missing something).

It would go from:

```rust
    assert_debug_snapshot_matches!(x.dimensions(), @r###"
   ⋮[
   ⋮    (
   ⋮        "x",
   ⋮        3,
   ⋮    ),
   ⋮    (
   ⋮        "y",
   ⋮        2,
   ⋮    ),
   ⋮]
    "###);
```

to:

```rust
    assert_debug_snapshot_matches!(x.dimensions(), @r###"
    [
        (
            "x",
            3,
        ),
        (
            "y",
            2,
        ),
    ]
    "###
```

So it removes the largest full rectangle of white space from both the result and reference, rather than any space prior to (& including) the `⋮` character.

I'm trying to grok the example above. If the reference value is currently

```
    ⋮foo
    ⋮  bar
```

...then we should fail on a value like...

```
  foo
  bar
```

Why would we get that unequal white space if the actual value had equal white space? Something to do with the first line of a multi-line string?

**Comment by mitsuhiko** [comment]
Special casing the first line does not work because that makes it impossible for you to have a higher amount of whitespace on the first line than on other:

```
   foo
  bar
 baz
blah
```

Is a good example of this.

**Comment by max-sixty** [comment]
To be clear on the proposal / functionality in ppx_expect, it's to remove "the largest rectangle of white space _in all lines_". So 

```
   foo
  bar
 baz
blah
```

is the same as 

```
    foo
   bar
  baz
 blah
```

...the later removing a single space from all lines. So it is easy to have different amounts of white space on different lines

Does that make sense?

**Comment by mitsuhiko** [comment]
This could potentially work but we still need to re-introduce the correct amount of whitespace before diffing.

**Comment by mitsuhiko** [comment]
@max-sixty since you asked in #62 what else to work on: i really like the idea of this ticket :)

**Comment by max-sixty** [comment]
> @max-sixty since you asked in #62 what else to work on: i really like the idea of this ticket :)

This is done! #52 ! Could do with a few more tests etc but let me know if you think it's in the right direction and I'll finish

**Comment by mitsuhiko** [comment]
@max-sixty Yeah. I think overall direction is pretty good. We need to make sure the diffing looks good and there is a good migration path over. But yeah, very much in favour.

**Comment by max-sixty** [comment]
OK cool!

**Comment by mitsuhiko** [comment]
We might even be able to improve on this by making a strict whitespace flag on the new settings if we run into any issues. For instance whitespace might play a vital role for such cases: https://github.com/brendanzab/codespan/blob/master/codespan-reporting/tests/snapshots/empty_spans__rich_no_color.snap

**Comment by max-sixty** [comment]
Plan for changes:
- Existing snapshots will still 'normalize', and so pass
- New snapshots will always write with rectangular space (even if the snapshot it's replacing was in the existing format)

**Comment by mitsuhiko** [comment]
@max-sixty i wonder if we can find a way to add something that upgrades all snapshots forcefully to latest. We could have a `INSTA_UPGRADE=1` which then forcefully writes back the latest format.  `cargo insta test --upgrade` could then auto upgrade.

**Comment by max-sixty** [comment]
> We might even be able to improve on this by making a strict whitespace flag on the new settings if we run into any issues. For instance whitespace might play a vital role for such cases: https://github.com/brendanzab/codespan/blob/master/codespan-reporting/tests/snapshots/empty_spans__rich_no_color.snap

Where would the flag go? 

To consider:
- It'll have false positives rather than false negatives. i.e. regardless of whitespace, tests will still pass, but won't fail on a difference between 

```
  x
```
and 
```
x
```

- If it's important, people can always use file snapshots
- Where whitespace is important, it's not going to look pretty, e.g.

```
              let y = "a"`
              assert_snapshot_matches!(x, r###"
test
###");
              let x = ...
```

**Comment by mitsuhiko** [comment]
@max-sixty into the new settings system:

```rust
insta::with_settings!({strict_whitespace = true, {
    ...
}));
```

It could just render out by prepending the string with a leading character that is otherwise ignored.

**Comment by max-sixty** [comment]
> @max-sixty i wonder if we can find a way to add something that upgrades all snapshots forcefully to latest. We could have a `INSTA_UPGRADE=1` which then forcefully writes back the latest format. `cargo insta test --upgrade` could then auto upgrade.

I very much agree with this, I was thinking about something similar: when you want to auto accept all changes.

So two ideas:
- `cargo insta test --accept` accepts all changes (or is there a way to do this already?)
- `cargo insta test --upgrade` overwrites with the newest format 

What are your thoughts?

**Comment by mitsuhiko** [comment]
Yeah, I think that makes sense adding. Right now we only have `cargo insta test` followed by `cargo insta accept`.

**Comment by max-sixty** [comment]
> @max-sixty into the new settings system:
> 
> ```rust
> insta::with_settings!({strict_whitespace = true}, {
>     ...
> });
> ```
> 
> It could just render out by prepending the string with a leading character that is otherwise ignored.

Yes we could definitely do that. Do you think it would be useful above doing file snapshots though? Those will still discriminate on white space.

**Comment by mitsuhiko** [comment]
@max-sixty it might be good enough to defer this for now and we just call it out.

**Comment by max-sixty** [comment]
> Yeah, I think that makes sense adding. Right now we only have `cargo insta test` followed by `cargo insta accept`.

OK cool. Do you think there's a simplicity to combining them? Or the ability to `--accept` is useful without overwriting everything?

**Comment by mitsuhiko** [comment]
I think adding `--accept` makes sense.
