### ISSUE TITLE
The extension does nothing if the crate is not in workspace root

### ISSUE THREAD

**Issue by necauqua** [mitsuhiko/insta#471]
### What happened?

If you have a monorepo or something similar (e.g. a tauri app) and you have your Rust code in a non-workspace-root folder - the vscode extension fails to detect that we have a cargo project that uses insta and does not find pending snaps etc.

### Reproduction steps

```bash
mkdir -p monorepo/rust-crate
cd monorepo/rust-crate
cargo init
cargo add --dev insta
cd ..
code .
```

### Insta Version

1.38.0

### rustc Version

1.76.0

### What did you expect?

I think the extension should detect folders with Cargo.toml (also consider workspaces ig) and use those as the rootUri instead of the workspace root.

Maybe communicate with rust-analyzer extension (if it's possible/simple, don't know much about vscode extensions) which definitely does detect cargo projects in the workspace and probably does so most robustly.

**Comment by mitsuhiko** [comment]
Yeah I also ran into that. Sadly I'm not super familiar with vscode extensions. I would love to get some assistance with fixing that.

**Comment by necauqua** [comment]
Ugh sure I wrote something :upside_down_face:
