### ISSUE TITLE
Group multiple assertions into one file

### ISSUE THREAD

**Issue by tisonkun** [mitsuhiko/insta#493]
Hi @mitsuhiko! Thanks for releasing this amazing crate for snapshot tests :D

I'm currently using insta to write SQL tests and assert the result set as snapshot. For demonstration, it looks like:

```
assert_snapshot!(execute("<sql-statements>"));

// result set
+------------+---------------+
| col_0::int | col_1::string |
+------------+---------------+
|         42 |       'tison' |
+------------+---------------+
```

This works well. But it generates one snapshot file per assertions, and I will have thousands of SQL statements to test and it creates too many files to store the snapshot.

Thus, I wonder if it's possible to group multiple assertions so that their snapshots are stored into one file.

Looking forward to your feedback.

**Comment by tisonkun** [comment]
Other solutions for SQL tests can be found like:

* https://github.com/GreptimeTeam/greptimedb/blob/main/tests/cases/standalone/common/basic.result
* https://github.com/risinglightdb/sqllogictest-rs/blob/main/tests/slt/basic.slt

Despite the DSL and inputs part, you may notice it contains multiple statements and all the output in one file.

**Comment by max-sixty** [comment]
Do inline snapshots help here? Over at PRQL we use them a lot for small snapshots...

**Comment by tisonkun** [comment]
@max-sixty Yeah ... This sounds reasonable and it would take almost the same lines like sqllogictest/sqlness linked above.

So snapshot files is mainly for large outputs and inline snapshots is encouraged for other scenarios?

**Comment by max-sixty** [comment]
> So snapshot files are mainly for large outputs and inline snapshots are encouraged for other scenarios?

Yes, that's how I generally think about them (though just my view, not necessarily the project's...)

**Comment by max-sixty** [comment]
I think this is fairly well covered by inline snapshots, so I'll close, but feel free to reopen if you disagree
