### ISSUE TITLE
Feature Request: Specify snapshot directory

### ISSUE THREAD

**Issue by ZoteTheMighty** [mitsuhiko/insta#50]
I'm working on a project that needs to snapshot multiple things for each test. I'd like to build some thin utility functions around the snapshots, but this results in them being placed within a utility folder.

I'm not sure what the mechanism might be, but I'd like to be able to specify where my snapshots are stored.

**Comment by aaronabramov** [comment]
is there any way to get current test context from Rust test runner?
i would expect snapshots to be stored in some nested directory that is also namespaced by target
e.g. 
```
snapshots/wasm/my_test.snap
snapshots/darwin/my_test.snap
```

**Comment by max-sixty** [comment]
Under what circumstances would you expect the snapshots to be different by target?

**Comment by aaronabramov** [comment]
i was thinking about testing default configuration based on the target.
e.g. if you're running a binary, grab that thing from the file system, if it's a wasm module, grab it from an ajax request etc.

although that might be better handled on a case by case basis manually to avoid extra complexity

**Comment by max-sixty** [comment]
Right - I with many libraries you'd want the same behavior on all targets. Where you want different behavior, you could supply different snapshot names. 

Maybe there's an abstraction that would make this case easier, but I wouldn't think we'd want a different path for each target by default...

**Comment by mitsuhiko** [comment]
I started work on thread local settings support. This could be used to move the snapshots elsewhere.
