### ISSUE TITLE
Change default merging style

### ISSUE THREAD

**Issue by max-sixty** [mitsuhiko/insta#522]
@mitsuhiko I realize I've merged a few PRs on the default merge style — which is Merge Commit — could we change this to Squash & Merge? And possibly only allow that?

<img width="177" alt="image" src="https://github.com/mitsuhiko/insta/assets/5635139/b68d02bb-6e4b-42f5-89dc-4eaebd111420">

Sorry the branch history is now messier. I should have checked more carefully. All the repos I maintain are set to always squash so I'm not in the habit of checking.

If you get to this immediately and really care, it's maybe fine to `push -f`, I've made a version with linear history at https://github.com/mitsuhiko/insta/commits/c94baa4f08a107cd31d207989d10a0e429d169f5/

**Comment by mitsuhiko** [comment]
Changed it to squash merge only.
