### ISSUE TITLE
sort order for unsorted collections

### ISSUE THREAD

**Issue by aaronabramov** [mitsuhiko/insta#53]
I'm working with graph traversal algorithms and snapshotting graph representations would make tests so much simpler.

one thing that i'm struggling with is snapshotting unsorted collections (like HashSet or HashMap)

for example if i snapshot a random HashSet, next time i run the test i'd get something like this:
<img width="234" alt="Screen Shot 2019-08-18 at 4 52 32 PM" src="https://user-images.githubusercontent.com/940133/63230294-ae20e980-c1d8-11e9-8569-f6c4c509381e.png">

the test fails, even though it's practically the same set

I'm new to rust and not sure if it's possible to overwrite serialize traits in test environment to sort them, but maybe as an alternative something can be done to a resulting json string

**Comment by max-sixty** [comment]
IIUC, could you use the `preserve_order` so the output is consistent? https://github.com/serde-rs/json/blob/master/Cargo.toml#L50

**Comment by mitsuhiko** [comment]
I'm not a huge fan of the `preserve_order` feature at all because that means turning it on or off will affect how stuff works. I wonder if it would be better to go via our internal `Content` abstraction and enforce ordering there in some situations.

**Comment by mitsuhiko** [comment]
Thinking about this more we could do something like this:

```rust
use insta;

let mut settings = insta::Settings::new();
settings.set_force_ordering(true);
insta::with_settings(&settings, || {
    insta::assert_ron_snapshots_matches!(...)
});
```

**Comment by mitsuhiko** [comment]
This works now on master: https://github.com/mitsuhiko/insta/blob/5d8f8c43098333645e4fe19b91872906f56461b5/tests/test_settings.rs#L4-L23
