### ISSUE TITLE
Redact string by regex matches

### ISSUE THREAD

**Issue by tisonkun** [mitsuhiko/insta#560]
Use case: I'd like to assert the error stack output as expected, it may look like:

```
Error: A fatal error has occurred in server process.
|-at cmd/xxx/src/command.rs:73:18
|
|-> failed to start server
|   |-at /Users/tison/xxx/xxx/crates/server/src/server.rs:140:14
|
|-> failed to refresh node group ...
|   |-at /Users/tison/xxx/xxx/crates/meta/src/service.rs:875:22
|
|-> node group does not exist: rw_group
    |-at /Users/tison/xxx/xxx/crates/meta/src/service.rs:642:13
    |-1 additional opaque attachment
```

Since line number is generally unstable, I wonder if we can redact the line/col number for a stable assertion.

I can see the out-of-the-box support in `insta` now: https://insta.rs/docs/redactions/

But it mainly redacts fields in structure assertion, while an error stack is a string.

**Comment by max-sixty** [comment]
Do filters do what you need?

**Comment by tisonkun** [comment]
@max-sixty https://insta.rs/docs/filters/ cool! Looks like exactly what I need.
