### ISSUE TITLE
Obsolete .new files are not removed

### ISSUE THREAD

**Issue by Y0hy0h** [mitsuhiko/insta#57]
I just ran insta with some changes that caused the comparison to fail. I then reverted these changes and the test passed again. However, the `.new` files from the broken state were still there. I compared them with the approved snapshot until I noticed that the `.new` one did not represent my code anymore, since I had reverted it.

I did not expect the `.new` files to refer to previous runs. I expect them to refer to the latest run. If the comparison fails, then the `.new` files will be overwritten as expected. It is only when the test passes anew while having previously failed that this issue occurs.

I would suggest removing existing `.new` files when a test passes to prevent this mistake of assuming they represent the current state of the code.

**Comment by max-sixty** [comment]
Could you try running the latest master? This may have been solved in https://github.com/mitsuhiko/insta/pull/48

**Comment by Y0hy0h** [comment]
Yes, this is the behavior on the master! I looked through the issues, but I didn't sift through the PRs, so I missed it.

Awesome! Thanks for being a step ahead of me. insta is really, really nice to use!

Closing since it is fixed in #48 and already merged into master.
