### ISSUE TITLE
`runner: nextest` in insta.yaml not being obeyed

### ISSUE THREAD

**Issue by Porges** [mitsuhiko/insta#572]
### What happened?

I haven't figured out/looked deeply into why this is happening yet but `runner: nextest` in my `insta.yaml` is not being obeyed.

### Reproduction steps

1. I have: `<repo>/insta.yaml`
```yaml
test:
  runner: nextest
```
2. I run `cargo insta test`.
3. It does not use `nextest`.

I verified that the YAML is being parsed by corrupting it and ensuring that `insta` fails.

### Insta Version

1.39.0

### rustc Version

nightly

### What did you expect?

The setting should be obeyed.

**Comment by max-sixty** [comment]
Fixed by https://github.com/mitsuhiko/insta/pull/544, just waiting on a release
