### ISSUE TITLE
Separate snapshot review binary?

### ISSUE THREAD

**Issue by thoughtpolice** [mitsuhiko/insta#576]
Would it be possible for the `cargo insta review` UX to be extracted in some form so that it could be run standalone? Is that already possible by just manually invoking the binary? As mentioned in https://github.com/mitsuhiko/insta/issues/575, I have a non-Cargo system at hand, so I'd like some way to apply fixes/review snapshot failures from the CLI.

If I can get around it by manually invoking `cargo-insta` that's probably doable for me in the mean time, but it's unclear if it would immediately work in a non-Cargo context.

**Comment by max-sixty** [comment]
@mitsuhiko will know more but to offer a quick response: I think `cargo-insta review` should in concept work fine without access to `cargo`.

One area where it uses `cargo` itself is in collecting the root of the workspace, when it calls `cargo metadata`. That's similar to the issues you hit in #575. My guess is that there are a couple of places where it doesn't yet initially check an env var — we'd be happy to adjust those so they are overridable by env vars. 

Worth noting that for file snapshots, `cargo-insta` isn't required — it's possible to have `insta` update them just by passing an env var https://docs.rs/insta/latest/insta/#use-without-cargo-insta — and then git makes a reasonable review interface.

**Comment by thoughtpolice** [comment]
Interesting, thanks! I also sat and realized that I could probably write my own tool within my codebase to review/apply snapshot files, so maybe that's also a reasonable possibility...

**Comment by max-sixty** [comment]
> I also sat and realized that I could probably write my own tool within my codebase to review/apply snapshot files, so maybe that's also a reasonable possibility...

`cargo-insta` is designed for this! So I would really think we should support this, happy to accept any changes, my guess is that it's < 10% of the work than making a new tool.

**Comment by max-sixty** [comment]
(will close but please comment with any follow-ups, particularly if you're thinking of writing your own snapshot review tool! :) )
