### ISSUE TITLE
insta 1.40.0 violates semver

### ISSUE THREAD

**Issue by xobs** [mitsuhiko/insta#591]
### What happened?

As mentioned in https://github.com/probe-rs/probe-rs/pull/2791#issuecomment-2338335525 and https://github.com/probe-rs/probe-rs/issues/2800#issuecomment-2336547115 -- the release of `1.40.0` changes the `serialize_yaml()` call so that it is no longer compatible with programs that built with `1.39.0`

Manually pinning `insta` to `1.39.0` fixes the issue.

**Comment by max-sixty** [comment]
I can look more later but for the moment: do you have any more details? A quick glance of the issue suggests you're using something other than the standard macros; is that correct?

(Technically that should indeed be covered by semver, but I think we've mostly focused on the macros themselves...)

**Comment by xobs** [comment]
I'm not sure. I'm a user of the program, and I didn't find much information when I tried to search the docs for the function that's failing.

The code does have this comment:

https://github.com/probe-rs/probe-rs/blob/d08dcd23141bfe7bfd7aab3996d4fba697d05168/probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/repl_commands.rs#L208-L219

```rust
            // Using the `insta` crate to serialize, because they add a couple of transformations to the yaml output,
            // presumeably to make it easier to read.
            // In our case, we want this backtrace format to be comparable to the unwind tests
            // in `probe-rs::debug::debuginfo`.
            // The reason for this is that these 'live' backtraces are used to create the 'master' snapshots,
            // which is used to compare against backtraces generated from coredumps.
            use insta::_macro_support as insta_yaml;
            let yaml_data = insta_yaml::serialize_value(
                &target_core.core_data.stack_frames,
                insta_yaml::SerializationFormat::Yaml,
                insta_yaml::SnapshotLocation::File,
            );
```

As a user of the program, I've had it report a build error that was fixed by pinning an earlier version, which is why I opened this issue.

**Comment by max-sixty** [comment]
OK yes, thanks a lot; that's a hidden function. These are de facto not covered by semver (e.g. https://predr.ag/blog/checking-semver-for-doc-hidden-items/).

Happy to consider how we could provide better APIs so that these internal items aren't required? It sounds like you're a (very helpful) user, so possibly someone who works on the code could open an issue?

(I will close for the moment, but feel free to add any comments here / reopen if I'm mistaken)

**Comment by max-sixty** [comment]
(And for the moment — I would recommend pinning to 1.39 and then making the small changes to pin to >=1.40...)
