### ISSUE TITLE
Feature request: inline snapshots

### ISSUE THREAD

**Issue by matklad** [mitsuhiko/insta#6]
Currently snapshots are stored in a separate files which is super-convenient for updating them, but makes reading the tests more difficult, because you don't have a test code and tests result near each other.

One could imagine a three argument form of `assert_debug_snaphot_mathes`, where the third argument is the text of the snapshot. It seems like this won't work, because updating the snapshot will require updating the source code, but perhaps it is possible? Snapshots have a well-defined header, so just grepping `src` for them should perhaps work? This sounds like a terrible idea, but I can see myself using it :)

**Comment by max-sixty** [comment]
This is similar to expect tests in OCaml. 

I made an attempt at this (before this library) to do this by using the `file!`-like macros and reading up the traceback but I found it difficult. I'd be up for making another go with some direction from someone who knows the language better

**Comment by mitsuhiko** [comment]
Yap, this is happening. I already started work on this but I first need to get some changes landed in proc-macro2: https://github.com/alexcrichton/proc-macro2/pull/165

**Comment by mitsuhiko** [comment]
This is implemented now on master.
