### ISSUE TITLE
binary & bitmap unit testing (for embedded)

### ISSUE THREAD

**Issue by ponyatov** [mitsuhiko/insta#604]
Is this crate suitable to test 
- binary data generation (custom filesystem) and 
- graphics primitives drawing on bitmaps (SDL-like surfaces)
- for embedded programming in Rust?

For 2D vector graphics render tests if would be great to have snaps in lossless & no-compression image formats to view it as is in VSCode or any other tool. (not shure is it possible for RGBA and narrow paletted colors).

**Comment by max-sixty** [comment]
There's some ongoing work to add binary snapshots: https://github.com/mitsuhiko/insta/issues/604

What are the requirements for this working on embedded systems? I've generally thought of embedded systems as not having access to `std`, and so no access to a file system — how would that work for binary snapshot tests?

**Comment by ponyatov** [comment]
> I've generally thought of embedded systems as not having access to `std`, and so no access to a file system

algorithmic parts can be isolated and tested on host with conditional compilation
- by comparing raw binary data fragments in memory
- using Linux FUSE (in case of filesystem dev)
- using some emulators (gdb target sim, QEMU,..) and gdb-stub API

Also `gdb` API allows to do some tests on a real hardware, but it looks too complex for implement.

**Comment by max-sixty** [comment]
OK, would it be possible to sketch out what that might look like, more specifically? Would we get the snapshot values with an `include_bytes!` call? How would that know where to look?

**Comment by max-sixty** [comment]
Feel free to reopen with ideas
