### ISSUE TITLE
Shorten to `assert_snapshot`?

### ISSUE THREAD

**Issue by max-sixty** [mitsuhiko/insta#63]
Feel free to shut this down, but when used frequently, `assert_snapshot_matches` or `assert_display_snapshot_matches` is a lot of characters (latter is 31, or ~40% of a full line).

Any interest in shortening to `assert_snapshot` / `assert_display_snapshot` / etc? There's no other viable comparison than a match / `eq`, so it could be OK to make that implicit.

(And we'd keep the existing as aliases)

**Comment by mitsuhiko** [comment]
Yeah, I think I would be in favor of this at this point. Those are quite long indeed.
