### ISSUE TITLE
1.41 release

### ISSUE THREAD

**Issue by max-sixty** [mitsuhiko/insta#646]
We should merge https://github.com/mitsuhiko/insta/pull/644, and then I think we can release.

(I would also like to get https://github.com/mitsuhiko/insta/pull/563 at some point, but nothing binding that to this release)

**Comment by mitsuhiko** [comment]
Sounds good!

**Comment by max-sixty** [comment]
OK, I merged #644, it's onto @mitsuhiko to release (or if you give me permissions I'm happy to do it...)

**Comment by max-sixty** [comment]
Actually give me a couple days, want to check everything is working correctly with #644, will add a couple tests.

**Comment by max-sixty** [comment]
OK, added some more tests, fixed a couple of small issues.

There are still things I'd like to look at — added some `TODO`s to the code, but I'm +1 to releasing

**Comment by max-sixty** [comment]
@mitsuhiko over to you :)

**Comment by max-sixty** [comment]
(I did this, closing)
