### ISSUE TITLE
Failed to release assets at 1.41.0

### ISSUE THREAD

**Issue by suzuki-shunsuke** [mitsuhiko/insta#677]
https://github.com/mitsuhiko/insta/releases/tag/1.41.0

<img width="278" alt="image" src="https://github.com/user-attachments/assets/f8803ee5-4847-490f-991a-3c7f6afb0167">

The release workflow failed.

https://github.com/mitsuhiko/insta/actions/runs/11544249635/job/32129653032

```
Run ncipollo/release-action@v1
Error: Error 422: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
```

**Comment by max-sixty** [comment]
Yes, that was unfortunate, it was my first time doing the release and I published a release rather than a tag.

I can release a 1.41.1 if the assets themselves would be helpful?

**Comment by suzuki-shunsuke** [comment]
> I can release a 1.41.1 if the assets themselves would be helpful?

Thank you. Yes, it would be helpful.
I'm a maintainer of [aqua](https://aquaproj.github.io/), which is a CLI version manager.
aqua supports insta, and users can update it by Renovate.
But currently, it fails to update insta to the latest version due to this issue.

e.g. https://github.com/aquaproj/aqua-registry/pull/28190 <- CI failed.

So I really appreciate it if you release 1.41.1.

**Comment by max-sixty** [comment]
Done! https://github.com/mitsuhiko/insta/releases/tag/1.41.1

Sorry for the inconvenience

**Comment by max-sixty** [comment]
(also aqua looks cool, nice work!)

**Comment by suzuki-shunsuke** [comment]
Thank you, nice work!
