### ISSUE TITLE
Settings::bind_to_scope()'s drop guard is Send

### ISSUE THREAD

**Issue by jalil-salame** [mitsuhiko/insta#694]
### What happened?

`Settings::bind_to_scope()`'s drop guard is `Send`, this means you can transfer it to a separate thread and break the settings like that.

This is not normally an issue, but using this in a multi-threaded executor like `tokio` could cause weird failures (when a future changes threads).

### Reproduction steps

1. `let guard = settings.bind_to_scope();`
2. `std::thread::spawn(move || { let _ = guard; })`
3. Observe settings in current thread are not reset.

### Insta Version

1.41.1

### rustc Version

1.83

### What did you expect?

`Settings::bind_to_scope()`'s drop guard should not be `Send` so this is prevented at compile time.

**Comment by max-sixty** [comment]
Thanks @jalil-salame . Would you be open to a PR?

**Comment by jalil-salame** [comment]
> Thanks @jalil-salame . Would you be open to a PR?

Sure! I should have time tomorrow
