### ISSUE TITLE
cargo-insta suggests 'cargo insta review' even in Cargo workspaces

### ISSUE THREAD

**Issue by LPGhatguy** [mitsuhiko/insta#71]
When I have snapshot failures in a project that is a Cargo workspace, it's necessary to run `cargo insta review --all` to review snapshots outside of the default crate.

Insta does not tell the user about `--all`, however, and still recommends `cargo insta review`. This erroneously indicates that there are no snapshots to review.

Would it be a good idea to make `cargo insta` operate on all packages by default? This behavior matches `cargo test` but feels very backwards, and I forget to pass in `--all` about a quarter of the time I'm using Insta.

**Comment by max-sixty** [comment]
Could you use [`default-members`](https://doc.rust-lang.org/cargo/reference/manifest.html#package-selection)? That would allow you to avoid passing `--all` each time.

I think deviating from the cargo default would be more confusing, even though I hear you re passing `--all` being inconvenient

**Comment by LPGhatguy** [comment]
Oh, I didn't know about `default-members`! That might solve a lot of problems for me in lots of projects, thanks!

**Comment by mitsuhiko** [comment]
`--all` should be implied. At least as per #30

**Comment by max-sixty** [comment]
IIUC `-all` is (& should be) implied _for virtual manifests_, rather than for normal workspaces
