### ISSUE TITLE
Feature request: Define redactions that can match values

### ISSUE THREAD

**Issue by LPGhatguy** [mitsuhiko/insta#73]
I have a project that's using insta to snapshot a tree. Each node in the tree has an ID that's randomly generated, and may hold references to other nodes via IDs.

Insta lets me redact all IDs with an expression like `"[.id]" = "[redacted id]"`, but this is a very heavy hammer. I lose any properties that happen to also have a key named `id`, and I can no longer snapshot that the inter-node relationships are correct.

It's possible in my case to turn those IDs into something deterministic, however, like using an incrementing number and deterministic tree traversal.

I'm okay generating a batch of redactions up-front with the settings API. Turning the `selector` argument of [`Settings::add_redaction`](https://docs.rs/insta/0.11.0/insta/struct.Settings.html#method.add_redaction) into a trait and providing a couple implementations could open up something like:

```rust
settings.add_redaction(
	Selector::new()
		.key_equal("id")
		.value_display_equal("75e60f48-d251-4717-969f-904f655581a8"),
	"[ID 0]",
);
```

Alternatively, being able to provide a callback would let me use the maps I generate dynamically instead of statically handing over a bunch of redactions to Insta:

```rust
settings.add_map_redaction(move |(key, value)| {
	if key == "id" {
		if let Some(new_value) = id_map.get(value.to_string().parse()) {
			return InstaData::String(new_value);
		}
	}

	value
});
```

**Comment by LPGhatguy** [comment]
I ended up rolling something like this for my project by using the `serde_yaml::Value` API:

https://github.com/rojo-rbx/rojo/blob/3678ddfa364aac3bbc1d6ec142f0926a0cd341e8/rojo-insta-ext/src/redaction_map.rs

**Comment by mitsuhiko** [comment]
I want to look into this. I think now that we expose this api through the settings we have the opportunity to add better assertions here.
