### ISSUE TITLE
support for non cargo based builds

### ISSUE THREAD

**Issue by aaronabramov** [mitsuhiko/insta#75]
i'm working on a project that builds with [Buck](https://buck.build/) i really want to use insta for my tests, unfortunately it seems like insta expects a lot of cargo env variables to be set and at some point it shells out to `cargo metadata --format-version=1 --no-deps` to get that `workspace_root`.

would it be possible to decouple it from cargo and have all env variables set manually for non-cargo builds?
i'm happy to do the work if that something this project would consider

**Comment by max-sixty** [comment]
I _think_ most of the cargo uses outside cargo-insta are for getting a root of the project, which I don't think necessarily needs to be coupled to cargo. 

Could we add an option to [those calls](https://github.com/mitsuhiko/insta/blob/master/src/runtime.rs#L143) with a single env var like `WORKSPACE_ROOT`?

**Comment by mitsuhiko** [comment]
@aaronabramov still interested in this? I would accept a patch, otherwise I would close this issue.

**Comment by aaronabramov** [comment]
@mitsuhiko it turned out to be more complicated because of all the project/workspace paths. I patched some things locally but i don't think it's worth a patch, and buck is probably not that popular as a build system :P
