### ISSUE TITLE
Snapshot macros called in different modules put snapshots into the wrong place

### ISSUE THREAD

**Issue by LPGhatguy** [mitsuhiko/insta#77]
I'm building a couple tools using Insta, and I want to package up the code I need to properly transform my data into a snapshottable form, and then run Insta's snapshot assertion functions on that data.

However, Insta puts those snapshot files relative to where the utility functions are defined, not relative to the test that's actually invoking them!

* My utility function is in `src/tree_view.rs`
* The code using the utility is in `src/commands/serve.rs` in a mod named `test`.
* The snapshots from that test end up in `src/snapshots` with a name like `tree_view__my_snapshot_name.snap`.

I would expect the snapshots to instead be put into `src/commands/snapshots` and have a name like `serve__my_snapshot_name.snap`.

**Comment by max-sixty** [comment]
Thanks for the issue @LPGhatguy . What does the utility function do? Do the utility functions call `assert_snapshot_x`?

**Comment by LPGhatguy** [comment]
They did call `assert_snapshot_x`! I ended up refactoring them to pull the actual snapshot assertion macro call into the outer block, which also lets me pass options like the snapshot name to the macro.

Previously:
```rust
fn snapshot_thing(thing: Thing) {
    let transformed = transform_thing(thing);
    let redacted = do_custom_redactions(transformed);
    assert_snapshot_yaml!(redacted);
}

#[test]
fn test_thing() {
    snapshot_thing(generate_thing());
}
```

Now:
```rust
fn view_thing(thing: Thing) -> RedactedThing {
    let transformed = transform_thing(thing);
    let redacted = do_custom_redactions(transformed);
    redacted
}

#[test]
fn test_thing() {
    assert_snapshot_yaml!(view_thing(generate_thing()));
}
```

**Comment by max-sixty** [comment]
Great! 

Would be interested in what redactions you use that `insta` doesn't yet support, too

**Comment by LPGhatguy** [comment]
@max-sixty The custom redactions are mostly around detecting specific values instead of keys.

I talked about it in #73 and also linked to the specific solution I had, which was kind of a heavy hammer but good enough for the problem I'm solving.

**Comment by max-sixty** [comment]
OK great. 

Are we OK to close this, in that case?

**Comment by LPGhatguy** [comment]
This issue still feels like an problem or footgun with Insta. Maybe this issue should spur a documentation entry that notes the two solutions to this problem:

1. Pull out your `assert_snapshot_x!` macro calls from the uility functions
2. Turn your snapshot utility functions into macros themselves

I'm not sure how Insta could solve this for the original code, since the assertion macros use the `file!()` macro to determine the snapshot output path. I don't think there are any other APIs along these lines in Rust. 😦

**Comment by max-sixty** [comment]
Right, it's going to name based on where the macro was called from. I'm not sure there's another way to design something that resolves the path itself...

**Comment by mitsuhiko** [comment]
Wouldn't the workaround here be to manually change the settings in the custom assertion macro or do we need to export extra information here?

**Comment by mitsuhiko** [comment]
Going to close this issue.
