### ISSUE TITLE
Tests inside 'test' mod pick up wrong name for snapshot name prefix

### ISSUE THREAD

**Issue by LPGhatguy** [mitsuhiko/insta#78]
If I define a test in a file like `src/foo.rs`, but my tests are in a `mod test` block, as is convention for Rust tests, the resulting snapshots are named with `test` as the prefix, not `foo`.

For example:

```rust
// src/foo.rs

pub fn add_one(value: u32) -> u32 {
    value + 1
}

#[cfg(test)]
mod test {
    use insta::assert_yaml_snapshot;

    #[test]
    fn it_adds_one() {
        let one = add_one(0);
        assert_yaml_snapshot!(one);
    }
}
```

The snapshot this test produces will be `src/snapshots/test__it_adds_one.snap`. It should be (and would be without the `mod test` wrapper) `src/snapshots/foo__it_adds_one.snap`.

This naming is problematic when there are multiple modules in the same folder that each have snapshot tests.

**Comment by max-sixty** [comment]
Right, we could change this function to add the file in place of / in addition to the module name: https://github.com/mitsuhiko/insta/blob/master/src/runtime.rs#L293-L306

**Comment by mitsuhiko** [comment]
@max-sixty do you want to give a stab at fixing this one?

**Comment by max-sixty** [comment]
Great @mitsuhiko, I'll have a go
