### ISSUE TITLE
`cargo insta review` fails with `Incorrect function. (os error 1)

### ISSUE THREAD

**Issue by MichaelMcDonnell** [mitsuhiko/insta#79]
I'm trying to update a snapshot with the `cargo insta review` but get the error message `Incorrect function. (os error 1). It only happens when I use Git Bash on Windows. Using cmd.exe works fine.

Steps to reproduce:

1. Open Git Bash on Windows
2. Change the directory to a project that has a snapshot test
3. Modify a test so the snapshot doesn't match
4. Run `cargo insta review`
5. Notice the normal message that the snapshot has changed and that you get options to accept, reject or skip.
6. Notice that you cannot enter your choice because of the error message `error: Incorrect function. (os error 1).

Again, using cmd.exe works fine.

**Comment by MichaelMcDonnell** [comment]
Two of my colleagues tried to reproduce it but it worked fine for them. There seem to be something odd about my machine. I've tried to remove MinGW from my path but I still get the same result.

**Comment by mitsuhiko** [comment]
I cannot reproduce this.

**Comment by MichaelMcDonnell** [comment]
I can also reproduce this on my home machine.

Any ideas how I can figure out what is going on? I do not see any logging in cargo-insta?

**Comment by mitsuhiko** [comment]
@MichaelMcDonnell first thing to try is if `RUST_BACKTRACE=1` shows something.

When I was googling for the issue I found this which suggested it might have something to do with the subsystem for linux: https://github.com/rust-lang/cargo/issues/7511 — so the culprits *might* be operations on the path. For instance we might canonicalize somewhere, where this is unsafe to do on windows.

**Comment by MichaelMcDonnell** [comment]
Thanks for your suggestion and the googling. That referenced issue sounds like what I'm seeing, except I'm not using WSL.

Using `RUST_BACKTRACE=1` did not do anything. I think that makes sense because it is not a panic.

I added some `println!` logs and it is the call to `read_key` in `query_snapshot` that fails. The `read_key` function is from the [`console`](https://crates.io/crates/console) crate. I'll try sometime soon to check that out and see what is going on.

**Comment by max-sixty** [comment]
(should we close? This is from 2019)

**Comment by MichaelMcDonnell** [comment]
Closing the issue. I'm not using `insta` anymore.
