### ISSUE TITLE
Dynamic redactions require use of internal types

### ISSUE THREAD

**Issue by LPGhatguy** [mitsuhiko/insta#89]
The new dynamic redactions feature in 0.12.0 is cool! However, it depends on the user interacting with types from the [`internals`](https://docs.rs/insta/0.12.0/insta/internals/index.html) module, notably `Redaction` and `Content`.

Additionally, `Content` has some variants that are explicitly hidden from documentation that are necessary to do some dynamic redactions, like `Content::NewtypeStruct`.

Are these types stable? Should I depend on them in my crate using Insta, or was depending on them an unintended artifact?

**Comment by mitsuhiko** [comment]
They are stable but they are mostly unnecessary which is why I placed them there.

**Comment by LPGhatguy** [comment]
There was recently some breakage in the `quote` crate that occurred when code used hidden members that were marked `pub` after [they were renamed](https://github.com/dtolnay/quote/commit/41543890aa76f4f8046fffac536b9445275aab26). I want to avoid having similar accidental breakage if I'm depending on these corners of insta in my projects!

Should the currently hidden variants of `Content` be documented and un-hidden? If the structs are stable and not library internals, should the module be renamed?

**Comment by mitsuhiko** [comment]
I added more public API for this. I hope this resolve these issues.
