### ISSUE TITLE
Snapshot name to include super modules?

### ISSUE THREAD

**Issue by ip1981** [mitsuhiko/insta#91]
I can see that snapshot names include module name (typically just `test`). I think there might be conflicts when a couple of modules at the same level have a "test" submodule with identical test functions. For example:

mod1.rs has a submodule "test" with a test "test_foo()"

and

mod2.rs  has a submodule "test" with a test "test_foo()".

There are few ways to avoid this situation: put modules into subdirectories, rename test submodules or test functions. But I think it could be the most convenient to have snapshot names include super modules too: `mod1__test__foo.snap`, `mod2__test__foo.snap`, etc.

**Comment by mitsuhiko** [comment]
This is fixed now on master.

**Comment by ip1981** [comment]
For reference, duplicates https://github.com/mitsuhiko/insta/issues/78.
