### ISSUE TITLE
Default snapshot filename is not working on Linux

### ISSUE THREAD

**Issue by sazzer** [mitsuhiko/insta#94]
I've got some tests using Insta, to test the output of templating for my webapp. On macOS these work just great, with filenames that are relevant to the test in question. (e.g. `tests__no_templates.snap`, `tests__simple_template.snap`, etc).

When I'm running the exact same build on my CI setup, which runs on Linux instead, this fails. And it fails because the filenames it is looking for are `tests__main.snap`, `tests__main-2.snap`, etc.

In both cases I'm using the latest nightly Cargo `cargo 1.41.0-nightly (626f0f40e 2019-12-03)` and Rust `rustc 1.42.0-nightly (0de96d37f 2019-12-19)`, and I'm using Insta 0.12.0, with a Cargo.lock file so CI should be using the identical version. I'm also doing all of the assertions with the `assert_debug_snapshot!` macro from the crate.

Cheers

**Comment by mitsuhiko** [comment]
Are your running your tests in a weird way? We're deriving the test name from the thread because there is no other way to do it and it sounds like your thread is named "main" instead of after the test.

**Comment by sazzer** [comment]
Nothing special. Was just running it on a GitLab runner was all. Not sure how that can be relevant though!

**Comment by mitsuhiko** [comment]
Absolutely cannot reproduce this. Do you have a repro case somewhere?

**Comment by mocsy** [comment]
> Nothing special. Was just running it on a GitLab runner was all. Not sure how that can be relevant though!

Are you using something like "image: rust:1.40" in your gitlab ci?
I have the same tests__main.snap probl;em on gitlab as well.
In my case my gitlab ruynner is on to of the same Ubuntu LTS that my development machine is.
So it's either the runner, or the rust image.

**Comment by sazzer** [comment]
I'm using `rustlang/rust:nightly-slim` for the image. It *might* also be environmental I guess - one of the environment properties that are set causing it to act differently? Do the threads get named differently if any of these are set? https://docs.gitlab.com/ee/ci/variables/predefined_variables.html - in particular I wonder about the `CI` one?

**Comment by mitsuhiko** [comment]
Would be great if someone can reproduce this. I'm not using gitlab myself.

**Comment by kjeremy** [comment]
I think I'm seeing the same thing here https://github.com/rust-analyzer/rust-analyzer/pull/2908

**Comment by mitsuhiko** [comment]
It looks like that if concurrency is disabled `rusttest` would run the test inline:

https://github.com/rust-lang/rust/blob/698fcd38fa9548e64a2092ff48c9d15ceb57d40c/src/libtest/lib.rs#L468-L474

This for instance would be a problem for wasm. I wonder if there is a way I can detect the test name without having to use the thread.

**Comment by mitsuhiko** [comment]
I "fixed" it through backtrace inspection which requires the `backtrace` feature to be enabled since it pulls in another dependency. Hope this resolves your issues.
