### ISSUE TITLE
Question: Every time insta creates new snapshots

### ISSUE THREAD

**Issue by SerhiiBilyk** [mitsuhiko/insta#95]
Hi, sorry for creating here an issue, but I think it worth.
Could you please take a look on [PR](https://github.com/imsnif/bandwhich/pull/112) ?
It is looks like `insta` every time creates new snapshots and dont using previous.
Could you please tell me what I'm doing wrong.
Ubuntu 18, rust 1.40

P.S. I'm not very experienced Rust programmer, so I'm sorry for taking your time.

**Comment by mitsuhiko** [comment]
Sorry I don't understand the question. Did you run `cargo insta accept`?

**Comment by SerhiiBilyk** [comment]
> Sorry I don't understand the question. Did you run `cargo insta accept`?

No I did not. Thanks for fast answer. I will try.
Every time I running cargo test, insta dont check existing snapshots but creates new.

**Comment by mitsuhiko** [comment]
Correct. You need to set `INSTA_UPDATE=always` if you want snapshots to update or you use `cargo insta review` (after installing `cargo-insta`) which is what I would recommend.

**Comment by SerhiiBilyk** [comment]
@mitsuhiko Thank you for your help! I'm struggled with this PR for long time! I'm very appreciate your help!
Some tests still failing, but I will handle it
